// Code generated by go-swagger; DO NOT EDIT.

package storage_metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/koyeb/koyeb-cli/pkg/kclient/models"
)

// GetStorageSummaryReader is a Reader for the GetStorageSummary structure.
type GetStorageSummaryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStorageSummaryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetStorageSummaryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetStorageSummaryBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetStorageSummaryForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetStorageSummaryNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetStorageSummaryOK creates a GetStorageSummaryOK with default headers values
func NewGetStorageSummaryOK() *GetStorageSummaryOK {
	return &GetStorageSummaryOK{}
}

/*GetStorageSummaryOK handles this case with default header values.

A successful response.
*/
type GetStorageSummaryOK struct {
	Payload *models.StorageStorageSummaryReply
}

func (o *GetStorageSummaryOK) Error() string {
	return fmt.Sprintf("[GET /v1/summary][%d] getStorageSummaryOK  %+v", 200, o.Payload)
}

func (o *GetStorageSummaryOK) GetPayload() *models.StorageStorageSummaryReply {
	return o.Payload
}

func (o *GetStorageSummaryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StorageStorageSummaryReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetStorageSummaryBadRequest creates a GetStorageSummaryBadRequest with default headers values
func NewGetStorageSummaryBadRequest() *GetStorageSummaryBadRequest {
	return &GetStorageSummaryBadRequest{}
}

/*GetStorageSummaryBadRequest handles this case with default header values.

Validation error
*/
type GetStorageSummaryBadRequest struct {
	Payload *models.CommonErrorWithFields
}

func (o *GetStorageSummaryBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/summary][%d] getStorageSummaryBadRequest  %+v", 400, o.Payload)
}

func (o *GetStorageSummaryBadRequest) GetPayload() *models.CommonErrorWithFields {
	return o.Payload
}

func (o *GetStorageSummaryBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonErrorWithFields)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetStorageSummaryForbidden creates a GetStorageSummaryForbidden with default headers values
func NewGetStorageSummaryForbidden() *GetStorageSummaryForbidden {
	return &GetStorageSummaryForbidden{}
}

/*GetStorageSummaryForbidden handles this case with default header values.

Returned when the user does not have permission to access the resource.
*/
type GetStorageSummaryForbidden struct {
	Payload *models.CommonError
}

func (o *GetStorageSummaryForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/summary][%d] getStorageSummaryForbidden  %+v", 403, o.Payload)
}

func (o *GetStorageSummaryForbidden) GetPayload() *models.CommonError {
	return o.Payload
}

func (o *GetStorageSummaryForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetStorageSummaryNotFound creates a GetStorageSummaryNotFound with default headers values
func NewGetStorageSummaryNotFound() *GetStorageSummaryNotFound {
	return &GetStorageSummaryNotFound{}
}

/*GetStorageSummaryNotFound handles this case with default header values.

Returned when the resource does not exist.
*/
type GetStorageSummaryNotFound struct {
	Payload *models.CommonError
}

func (o *GetStorageSummaryNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/summary][%d] getStorageSummaryNotFound  %+v", 404, o.Payload)
}

func (o *GetStorageSummaryNotFound) GetPayload() *models.CommonError {
	return o.Payload
}

func (o *GetStorageSummaryNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
