// Code generated by go-swagger; DO NOT EDIT.

package storage_metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new storage metrics API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for storage metrics API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	StorageMetricsGetStorageSummary(params *StorageMetricsGetStorageSummaryParams, authInfo runtime.ClientAuthInfoWriter) (*StorageMetricsGetStorageSummaryOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  StorageMetricsGetStorageSummary storage metrics get storage summary API
*/
func (a *Client) StorageMetricsGetStorageSummary(params *StorageMetricsGetStorageSummaryParams, authInfo runtime.ClientAuthInfoWriter) (*StorageMetricsGetStorageSummaryOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStorageMetricsGetStorageSummaryParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "StorageMetrics_GetStorageSummary",
		Method:             "GET",
		PathPattern:        "/v1/summary",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &StorageMetricsGetStorageSummaryReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*StorageMetricsGetStorageSummaryOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*StorageMetricsGetStorageSummaryDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
