// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/koyeb/koyeb-cli/pkg/kclient/models"
)

// NewOrganizationCreateBillingInfoParams creates a new OrganizationCreateBillingInfoParams object
// with the default values initialized.
func NewOrganizationCreateBillingInfoParams() *OrganizationCreateBillingInfoParams {
	var ()
	return &OrganizationCreateBillingInfoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOrganizationCreateBillingInfoParamsWithTimeout creates a new OrganizationCreateBillingInfoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOrganizationCreateBillingInfoParamsWithTimeout(timeout time.Duration) *OrganizationCreateBillingInfoParams {
	var ()
	return &OrganizationCreateBillingInfoParams{

		timeout: timeout,
	}
}

// NewOrganizationCreateBillingInfoParamsWithContext creates a new OrganizationCreateBillingInfoParams object
// with the default values initialized, and the ability to set a context for a request
func NewOrganizationCreateBillingInfoParamsWithContext(ctx context.Context) *OrganizationCreateBillingInfoParams {
	var ()
	return &OrganizationCreateBillingInfoParams{

		Context: ctx,
	}
}

// NewOrganizationCreateBillingInfoParamsWithHTTPClient creates a new OrganizationCreateBillingInfoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOrganizationCreateBillingInfoParamsWithHTTPClient(client *http.Client) *OrganizationCreateBillingInfoParams {
	var ()
	return &OrganizationCreateBillingInfoParams{
		HTTPClient: client,
	}
}

/*OrganizationCreateBillingInfoParams contains all the parameters to send to the API endpoint
for the organization create billing info operation typically these are written to a http.Request
*/
type OrganizationCreateBillingInfoParams struct {

	/*Body*/
	Body *models.AccountCreateBillingInfoRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the organization create billing info params
func (o *OrganizationCreateBillingInfoParams) WithTimeout(timeout time.Duration) *OrganizationCreateBillingInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the organization create billing info params
func (o *OrganizationCreateBillingInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the organization create billing info params
func (o *OrganizationCreateBillingInfoParams) WithContext(ctx context.Context) *OrganizationCreateBillingInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the organization create billing info params
func (o *OrganizationCreateBillingInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the organization create billing info params
func (o *OrganizationCreateBillingInfoParams) WithHTTPClient(client *http.Client) *OrganizationCreateBillingInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the organization create billing info params
func (o *OrganizationCreateBillingInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the organization create billing info params
func (o *OrganizationCreateBillingInfoParams) WithBody(body *models.AccountCreateBillingInfoRequest) *OrganizationCreateBillingInfoParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the organization create billing info params
func (o *OrganizationCreateBillingInfoParams) SetBody(body *models.AccountCreateBillingInfoRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *OrganizationCreateBillingInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
