// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/koyeb/koyeb-cli/pkg/kclient/models"
)

// OrganizationUpdateBillingReader is a Reader for the OrganizationUpdateBilling structure.
type OrganizationUpdateBillingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrganizationUpdateBillingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOrganizationUpdateBillingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewOrganizationUpdateBillingBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewOrganizationUpdateBillingForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewOrganizationUpdateBillingNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewOrganizationUpdateBillingDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewOrganizationUpdateBillingOK creates a OrganizationUpdateBillingOK with default headers values
func NewOrganizationUpdateBillingOK() *OrganizationUpdateBillingOK {
	return &OrganizationUpdateBillingOK{}
}

/*OrganizationUpdateBillingOK handles this case with default header values.

A successful response.
*/
type OrganizationUpdateBillingOK struct {
	Payload *models.AccountBillingInfoReply
}

func (o *OrganizationUpdateBillingOK) Error() string {
	return fmt.Sprintf("[PUT /v1/account/billing][%d] organizationUpdateBillingOK  %+v", 200, o.Payload)
}

func (o *OrganizationUpdateBillingOK) GetPayload() *models.AccountBillingInfoReply {
	return o.Payload
}

func (o *OrganizationUpdateBillingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AccountBillingInfoReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOrganizationUpdateBillingBadRequest creates a OrganizationUpdateBillingBadRequest with default headers values
func NewOrganizationUpdateBillingBadRequest() *OrganizationUpdateBillingBadRequest {
	return &OrganizationUpdateBillingBadRequest{}
}

/*OrganizationUpdateBillingBadRequest handles this case with default header values.

Validation error
*/
type OrganizationUpdateBillingBadRequest struct {
	Payload *models.CommonErrorWithFields
}

func (o *OrganizationUpdateBillingBadRequest) Error() string {
	return fmt.Sprintf("[PUT /v1/account/billing][%d] organizationUpdateBillingBadRequest  %+v", 400, o.Payload)
}

func (o *OrganizationUpdateBillingBadRequest) GetPayload() *models.CommonErrorWithFields {
	return o.Payload
}

func (o *OrganizationUpdateBillingBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonErrorWithFields)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOrganizationUpdateBillingForbidden creates a OrganizationUpdateBillingForbidden with default headers values
func NewOrganizationUpdateBillingForbidden() *OrganizationUpdateBillingForbidden {
	return &OrganizationUpdateBillingForbidden{}
}

/*OrganizationUpdateBillingForbidden handles this case with default header values.

Returned when the user does not have permission to access the resource.
*/
type OrganizationUpdateBillingForbidden struct {
	Payload *models.CommonError
}

func (o *OrganizationUpdateBillingForbidden) Error() string {
	return fmt.Sprintf("[PUT /v1/account/billing][%d] organizationUpdateBillingForbidden  %+v", 403, o.Payload)
}

func (o *OrganizationUpdateBillingForbidden) GetPayload() *models.CommonError {
	return o.Payload
}

func (o *OrganizationUpdateBillingForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOrganizationUpdateBillingNotFound creates a OrganizationUpdateBillingNotFound with default headers values
func NewOrganizationUpdateBillingNotFound() *OrganizationUpdateBillingNotFound {
	return &OrganizationUpdateBillingNotFound{}
}

/*OrganizationUpdateBillingNotFound handles this case with default header values.

Returned when the resource does not exist.
*/
type OrganizationUpdateBillingNotFound struct {
	Payload *models.CommonError
}

func (o *OrganizationUpdateBillingNotFound) Error() string {
	return fmt.Sprintf("[PUT /v1/account/billing][%d] organizationUpdateBillingNotFound  %+v", 404, o.Payload)
}

func (o *OrganizationUpdateBillingNotFound) GetPayload() *models.CommonError {
	return o.Payload
}

func (o *OrganizationUpdateBillingNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOrganizationUpdateBillingDefault creates a OrganizationUpdateBillingDefault with default headers values
func NewOrganizationUpdateBillingDefault(code int) *OrganizationUpdateBillingDefault {
	return &OrganizationUpdateBillingDefault{
		_statusCode: code,
	}
}

/*OrganizationUpdateBillingDefault handles this case with default header values.

An unexpected error response
*/
type OrganizationUpdateBillingDefault struct {
	_statusCode int

	Payload *models.GatewayruntimeError
}

// Code gets the status code for the organization update billing default response
func (o *OrganizationUpdateBillingDefault) Code() int {
	return o._statusCode
}

func (o *OrganizationUpdateBillingDefault) Error() string {
	return fmt.Sprintf("[PUT /v1/account/billing][%d] organization_UpdateBilling default  %+v", o._statusCode, o.Payload)
}

func (o *OrganizationUpdateBillingDefault) GetPayload() *models.GatewayruntimeError {
	return o.Payload
}

func (o *OrganizationUpdateBillingDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GatewayruntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
