version: "2"

linters:
  exclusions:
    rules:
      - linters:
          - errcheck
        text: "Error return value of `.*\\.Close` is not checked"
      - linters:
          - errcheck
        text: "Error return value of `os\\.Stdout\\.Write` is not checked"
      - linters:
          - errcheck
        text: "Error return value of `rand\\.Read` is not checked"
