version: 2
builds:
  - id: koyeb
    builder: rust
    binary: koyeb
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-apple-darwin
      - aarch64-apple-darwin
      - x86_64-pc-windows-msvc
archives:
  - id: default
    builds: [koyeb]
    wrap_in_directory: false
    formats: [tar.gz]
  - id: windows
    builds: [koyeb]
    wrap_in_directory: false
    formats: [zip]
release:
  prerelease: auto
  header: |
    ## The best version ever of Koyeb CLI is here!

    Welcome to this new release!
    Check the changelog in [CHANGES.md](https://github.com/koyeb/koyeb-cli/blob/master/CHANGES.md) for more details.
    For upgrade instructions, see [README.md](https://github.com/koyeb/koyeb-cli/blob/master/README.md).
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{.Branch}}-{{.ShortCommit}}"
brews:
  - repository:
      owner: koyeb
      name: homebrew-tap
    name: koyeb
    directory: Formula
    homepage: https://koyeb.com
    skip_upload: auto
    test: |
      system "#{bin}/koyeb version"
    install: |
      bin.install "koyeb"
