name: test-compose-service
services:
  myservicee:
    docker:
      image: nginx
    ports:
      - port: 80
    regions: ['par']
    scalings:
      - scopes: ['region:par']
        min: 1
        max: 1
    instance_types:
      - scopes: ['region:par']
        type: 'nano'
    
