use assert_cmd::Command;

const OLD_REFERENCE_COMMANDS: &[&[&str]] = &[
    &[],
    &["login"],
    &["apps"],
    &["apps", "create"],
    &["apps", "delete"],
    &["apps", "describe"],
    &["apps", "get"],
    &["apps", "init"],
    &["apps", "list"],
    &["apps", "pause"],
    &["apps", "resume"],
    &["apps", "update"],
    &["archives"],
    &["archives", "create"],
    &["deploy"],
    &["domains"],
    &["domains", "attach"],
    &["domains", "create"],
    &["domains", "delete"],
    &["domains", "describe"],
    &["domains", "detach"],
    &["domains", "get"],
    &["domains", "list"],
    &["domains", "refresh"],
    &["organizations"],
    &["organizations", "list"],
    &["organizations", "switch"],
    &["secrets"],
    &["secrets", "create"],
    &["secrets", "delete"],
    &["secrets", "describe"],
    &["secrets", "get"],
    &["secrets", "list"],
    &["secrets", "reveal"],
    &["secrets", "update"],
    &["services"],
    &["services", "create"],
    &["services", "delete"],
    &["services", "describe"],
    &["services", "exec"],
    &["services", "get"],
    &["services", "list"],
    &["services", "logs"],
    &["services", "pause"],
    &["services", "redeploy"],
    &["services", "resume"],
    &["services", "unapplied-changes"],
    &["services", "update"],
    &["services", "scale"],
    &["services", "scale", "delete"],
    &["services", "scale", "get"],
    &["services", "scale", "update"],
    &["deployments"],
    &["deployments", "cancel"],
    &["deployments", "describe"],
    &["deployments", "get"],
    &["deployments", "list"],
    &["deployments", "logs"],
    &["instances"],
    &["instances", "cp"],
    &["instances", "describe"],
    &["instances", "exec"],
    &["instances", "get"],
    &["instances", "list"],
    &["instances", "logs"],
    &["databases"],
    &["databases", "create"],
    &["databases", "delete"],
    &["databases", "get"],
    &["databases", "list"],
    &["databases", "update"],
    &["sandbox"],
    &["sandbox", "create"],
    &["sandbox", "expose-port"],
    &["sandbox", "fs", "download"],
    &["sandbox", "fs", "ls"],
    &["sandbox", "fs", "mkdir"],
    &["sandbox", "fs", "read"],
    &["sandbox", "fs", "rm"],
    &["sandbox", "fs", "upload"],
    &["sandbox", "fs", "write"],
    &["sandbox", "fs"],
    &["sandbox", "health"],
    &["sandbox", "kill"],
    &["sandbox", "list"],
    &["sandbox", "logs"],
    &["sandbox", "ps"],
    &["sandbox", "run"],
    &["sandbox", "start"],
    &["sandbox", "unexpose-port"],
    &["version"],
    &["volumes"],
    &["whoami"],
];

const OLD_ALIASES: &[(&[&str], &[&str])] = &[
    (
        &[],
        &[
            "a",
            "app",
            "archive",
            "dom",
            "domain",
            "organization",
            "orgas",
            "orga",
            "orgs",
            "org",
            "organisations",
            "organisation",
            "sec",
            "secret",
            "s",
            "svc",
            "service",
            "d",
            "dep",
            "depl",
            "deployment",
            "rd",
            "rdep",
            "rdepl",
            "rdeploy",
            "rdeployment",
            "regional-deployment",
            "i",
            "inst",
            "instance",
            "db",
            "database",
            "metric",
            "vol",
            "volume",
            "snapshot",
            "sb",
        ],
    ),
    (&["services"], &["l", "log", "run", "attach"]),
    (&["deployments"], &["l", "log"]),
    (&["instances"], &["run", "attach", "copy", "l", "log"]),
    (&["secrets"], &["show"]),
    (&["sandbox"], &["launch", "list-processes", "filesystem"]),
];

const REQUIRED_FLAGS: &[(&[&str], &[&str])] = &[
    (
        &["apps", "init"],
        &[
            "--git-buildpack-build-command",
            "--git-buildpack-run-command",
            "--git-workdir",
            "--git-no-deploy-on-push",
            "--git-docker-command",
            "--git-docker-target",
            "--docker-private-registry-secret",
            "--docker-skip-verify",
            "--docker-command",
            "--archive-buildpack-build-command",
            "--archive-buildpack-run-command",
            "--archive-docker-command",
            "--archive-docker-target",
            "--deployment-strategy",
            "--auth",
            "--auth-disable",
            "--autoscaling-average-cpu",
            "--autoscaling-average-mem",
            "--autoscaling-requests-per-second",
            "--autoscaling-concurrent-requests",
            "--autoscaling-requests-response-time",
            "--port",
            "--region",
            "--route",
            "--volume",
            "--type",
        ],
    ),
    (
        &["deploy"],
        &[
            "--archive-buildpack-build-command",
            "--archive-buildpack-run-command",
            "--archive-docker-command",
            "--archive-docker-target",
            "--deployment-strategy",
            "--auth",
            "--auth-disable",
            "--autoscaling-average-cpu",
            "--autoscaling-average-mem",
            "--autoscaling-requests-per-second",
            "--autoscaling-concurrent-requests",
            "--autoscaling-requests-response-time",
            "--port",
            "--region",
            "--route",
            "--volume",
            "--type",
        ],
    ),
    (
        &["services", "create"],
        &[
            "--git-buildpack-build-command",
            "--git-buildpack-run-command",
            "--git-workdir",
            "--git-no-deploy-on-push",
            "--git-docker-command",
            "--git-docker-target",
            "--docker-private-registry-secret",
            "--docker-skip-verify",
            "--docker-command",
            "--archive-buildpack-build-command",
            "--archive-buildpack-run-command",
            "--archive-docker-command",
            "--archive-docker-target",
            "--deployment-strategy",
            "--auth",
            "--auth-disable",
            "--autoscaling-average-cpu",
            "--autoscaling-average-mem",
            "--autoscaling-requests-per-second",
            "--autoscaling-concurrent-requests",
            "--autoscaling-requests-response-time",
            "--port",
            "--region",
            "--route",
            "--volume",
            "--type",
        ],
    ),
    (
        &["services", "update"],
        &[
            "--git-buildpack-build-command",
            "--git-buildpack-run-command",
            "--git-workdir",
            "--git-no-deploy-on-push",
            "--git-docker-command",
            "--git-docker-target",
            "--docker-private-registry-secret",
            "--docker-skip-verify",
            "--docker-command",
            "--archive-buildpack-build-command",
            "--archive-buildpack-run-command",
            "--archive-docker-command",
            "--archive-docker-target",
            "--deployment-strategy",
            "--auth",
            "--auth-disable",
            "--autoscaling-average-cpu",
            "--autoscaling-average-mem",
            "--autoscaling-requests-per-second",
            "--autoscaling-concurrent-requests",
            "--autoscaling-requests-response-time",
            "--port",
            "--region",
            "--route",
            "--volume",
            "--type",
        ],
    ),
    (
        &["secrets", "create"],
        &[
            "--type",
            "--value",
            "--value-from-stdin",
            "--registry-username",
            "--registry-url",
            "--registry-keyfile",
            "--registry-name",
        ],
    ),
    (
        &["secrets", "update"],
        &[
            "--type",
            "--value",
            "--value-from-stdin",
            "--registry-username",
            "--registry-url",
            "--registry-keyfile",
            "--registry-name",
        ],
    ),
    (&["deployments", "logs"], &["--since"]),
    (&["instances", "logs"], &["--since"]),
    (&["databases", "create"], &["--name"]),
    (&["databases", "update"], &["--app"]),
    (
        &["sandbox", "create"],
        &[
            "--app",
            "--wait",
            "--docker-command",
            "--docker-private-registry-secret",
            "--instance-type",
            "--min-scale",
            "--privileged",
        ],
    ),
];

#[test]
fn old_reference_commands_are_available() {
    for command in OLD_REFERENCE_COMMANDS {
        let mut cmd = Command::cargo_bin("koyeb").unwrap();
        cmd.args(*command).arg("--help").assert().success();
    }
}

#[test]
fn old_aliases_are_available() {
    for (prefix, aliases) in OLD_ALIASES {
        for alias in *aliases {
            let mut cmd = Command::cargo_bin("koyeb").unwrap();
            cmd.args(*prefix)
                .arg(alias)
                .arg("--help")
                .assert()
                .success();
        }
    }
}

#[test]
fn old_flags_are_available_on_equivalent_commands() {
    for (command, flags) in REQUIRED_FLAGS {
        let mut help = Command::cargo_bin("koyeb").unwrap();
        let output = help.args(*command).arg("--help").output().unwrap();
        assert!(output.status.success(), "help failed for {:?}", command);
        let stdout = String::from_utf8(output.stdout).unwrap();
        for flag in *flags {
            assert!(
                stdout.contains(flag),
                "missing {flag} in help for {:?}",
                command
            );
        }
    }
}
