// Code generated by go-swagger; DO NOT EDIT.

package deliveries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDeliveryParams creates a new GetDeliveryParams object
// with the default values initialized.
func NewGetDeliveryParams() *GetDeliveryParams {
	var ()
	return &GetDeliveryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDeliveryParamsWithTimeout creates a new GetDeliveryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDeliveryParamsWithTimeout(timeout time.Duration) *GetDeliveryParams {
	var ()
	return &GetDeliveryParams{

		timeout: timeout,
	}
}

// NewGetDeliveryParamsWithContext creates a new GetDeliveryParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDeliveryParamsWithContext(ctx context.Context) *GetDeliveryParams {
	var ()
	return &GetDeliveryParams{

		Context: ctx,
	}
}

// NewGetDeliveryParamsWithHTTPClient creates a new GetDeliveryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDeliveryParamsWithHTTPClient(client *http.Client) *GetDeliveryParams {
	var ()
	return &GetDeliveryParams{
		HTTPClient: client,
	}
}

/*GetDeliveryParams contains all the parameters to send to the API endpoint
for the get delivery operation typically these are written to a http.Request
*/
type GetDeliveryParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get delivery params
func (o *GetDeliveryParams) WithTimeout(timeout time.Duration) *GetDeliveryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get delivery params
func (o *GetDeliveryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get delivery params
func (o *GetDeliveryParams) WithContext(ctx context.Context) *GetDeliveryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get delivery params
func (o *GetDeliveryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get delivery params
func (o *GetDeliveryParams) WithHTTPClient(client *http.Client) *GetDeliveryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get delivery params
func (o *GetDeliveryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get delivery params
func (o *GetDeliveryParams) WithID(id string) *GetDeliveryParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get delivery params
func (o *GetDeliveryParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetDeliveryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
