// Code generated by go-swagger; DO NOT EDIT.

package deliveries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/koyeb/koyeb-cli/pkg/kclient/models"
)

// ListDeliveriesReader is a Reader for the ListDeliveries structure.
type ListDeliveriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListDeliveriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListDeliveriesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListDeliveriesOK creates a ListDeliveriesOK with default headers values
func NewListDeliveriesOK() *ListDeliveriesOK {
	return &ListDeliveriesOK{}
}

/*ListDeliveriesOK handles this case with default header values.

A successful response.
*/
type ListDeliveriesOK struct {
	Payload *models.StorageListDeliveriesReply
}

func (o *ListDeliveriesOK) Error() string {
	return fmt.Sprintf("[GET /v1/deliveries][%d] listDeliveriesOK  %+v", 200, o.Payload)
}

func (o *ListDeliveriesOK) GetPayload() *models.StorageListDeliveriesReply {
	return o.Payload
}

func (o *ListDeliveriesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StorageListDeliveriesReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
