// Code generated by go-swagger; DO NOT EDIT.

package deliveries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/koyeb/koyeb-cli/pkg/kclient/models"
)

// NewUpdateDelivery2Params creates a new UpdateDelivery2Params object
// with the default values initialized.
func NewUpdateDelivery2Params() *UpdateDelivery2Params {
	var ()
	return &UpdateDelivery2Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateDelivery2ParamsWithTimeout creates a new UpdateDelivery2Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateDelivery2ParamsWithTimeout(timeout time.Duration) *UpdateDelivery2Params {
	var ()
	return &UpdateDelivery2Params{

		timeout: timeout,
	}
}

// NewUpdateDelivery2ParamsWithContext creates a new UpdateDelivery2Params object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateDelivery2ParamsWithContext(ctx context.Context) *UpdateDelivery2Params {
	var ()
	return &UpdateDelivery2Params{

		Context: ctx,
	}
}

// NewUpdateDelivery2ParamsWithHTTPClient creates a new UpdateDelivery2Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateDelivery2ParamsWithHTTPClient(client *http.Client) *UpdateDelivery2Params {
	var ()
	return &UpdateDelivery2Params{
		HTTPClient: client,
	}
}

/*UpdateDelivery2Params contains all the parameters to send to the API endpoint
for the update delivery2 operation typically these are written to a http.Request
*/
type UpdateDelivery2Params struct {

	/*Body*/
	Body *models.StorageDeliveryBody
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update delivery2 params
func (o *UpdateDelivery2Params) WithTimeout(timeout time.Duration) *UpdateDelivery2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update delivery2 params
func (o *UpdateDelivery2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update delivery2 params
func (o *UpdateDelivery2Params) WithContext(ctx context.Context) *UpdateDelivery2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update delivery2 params
func (o *UpdateDelivery2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update delivery2 params
func (o *UpdateDelivery2Params) WithHTTPClient(client *http.Client) *UpdateDelivery2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update delivery2 params
func (o *UpdateDelivery2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update delivery2 params
func (o *UpdateDelivery2Params) WithBody(body *models.StorageDeliveryBody) *UpdateDelivery2Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update delivery2 params
func (o *UpdateDelivery2Params) SetBody(body *models.StorageDeliveryBody) {
	o.Body = body
}

// WithID adds the id to the update delivery2 params
func (o *UpdateDelivery2Params) WithID(id string) *UpdateDelivery2Params {
	o.SetID(id)
	return o
}

// SetID adds the id to the update delivery2 params
func (o *UpdateDelivery2Params) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateDelivery2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
