// Code generated by go-swagger; DO NOT EDIT.

package managed_stores

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteManagedStoreParams creates a new DeleteManagedStoreParams object
// with the default values initialized.
func NewDeleteManagedStoreParams() *DeleteManagedStoreParams {
	var ()
	return &DeleteManagedStoreParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteManagedStoreParamsWithTimeout creates a new DeleteManagedStoreParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteManagedStoreParamsWithTimeout(timeout time.Duration) *DeleteManagedStoreParams {
	var ()
	return &DeleteManagedStoreParams{

		timeout: timeout,
	}
}

// NewDeleteManagedStoreParamsWithContext creates a new DeleteManagedStoreParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteManagedStoreParamsWithContext(ctx context.Context) *DeleteManagedStoreParams {
	var ()
	return &DeleteManagedStoreParams{

		Context: ctx,
	}
}

// NewDeleteManagedStoreParamsWithHTTPClient creates a new DeleteManagedStoreParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteManagedStoreParamsWithHTTPClient(client *http.Client) *DeleteManagedStoreParams {
	var ()
	return &DeleteManagedStoreParams{
		HTTPClient: client,
	}
}

/*DeleteManagedStoreParams contains all the parameters to send to the API endpoint
for the delete managed store operation typically these are written to a http.Request
*/
type DeleteManagedStoreParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete managed store params
func (o *DeleteManagedStoreParams) WithTimeout(timeout time.Duration) *DeleteManagedStoreParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete managed store params
func (o *DeleteManagedStoreParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete managed store params
func (o *DeleteManagedStoreParams) WithContext(ctx context.Context) *DeleteManagedStoreParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete managed store params
func (o *DeleteManagedStoreParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete managed store params
func (o *DeleteManagedStoreParams) WithHTTPClient(client *http.Client) *DeleteManagedStoreParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete managed store params
func (o *DeleteManagedStoreParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete managed store params
func (o *DeleteManagedStoreParams) WithID(id string) *DeleteManagedStoreParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete managed store params
func (o *DeleteManagedStoreParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteManagedStoreParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
