// Code generated by go-swagger; DO NOT EDIT.

package managed_stores

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/koyeb/koyeb-cli/pkg/kclient/models"
)

// NewNewManagedStoreParams creates a new NewManagedStoreParams object
// with the default values initialized.
func NewNewManagedStoreParams() *NewManagedStoreParams {
	var ()
	return &NewManagedStoreParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewNewManagedStoreParamsWithTimeout creates a new NewManagedStoreParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewNewManagedStoreParamsWithTimeout(timeout time.Duration) *NewManagedStoreParams {
	var ()
	return &NewManagedStoreParams{

		timeout: timeout,
	}
}

// NewNewManagedStoreParamsWithContext creates a new NewManagedStoreParams object
// with the default values initialized, and the ability to set a context for a request
func NewNewManagedStoreParamsWithContext(ctx context.Context) *NewManagedStoreParams {
	var ()
	return &NewManagedStoreParams{

		Context: ctx,
	}
}

// NewNewManagedStoreParamsWithHTTPClient creates a new NewManagedStoreParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNewManagedStoreParamsWithHTTPClient(client *http.Client) *NewManagedStoreParams {
	var ()
	return &NewManagedStoreParams{
		HTTPClient: client,
	}
}

/*NewManagedStoreParams contains all the parameters to send to the API endpoint
for the new managed store operation typically these are written to a http.Request
*/
type NewManagedStoreParams struct {

	/*Body*/
	Body *models.StorageNewManagedStoreBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the new managed store params
func (o *NewManagedStoreParams) WithTimeout(timeout time.Duration) *NewManagedStoreParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the new managed store params
func (o *NewManagedStoreParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the new managed store params
func (o *NewManagedStoreParams) WithContext(ctx context.Context) *NewManagedStoreParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the new managed store params
func (o *NewManagedStoreParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the new managed store params
func (o *NewManagedStoreParams) WithHTTPClient(client *http.Client) *NewManagedStoreParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the new managed store params
func (o *NewManagedStoreParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the new managed store params
func (o *NewManagedStoreParams) WithBody(body *models.StorageNewManagedStoreBody) *NewManagedStoreParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the new managed store params
func (o *NewManagedStoreParams) SetBody(body *models.StorageNewManagedStoreBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *NewManagedStoreParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
