// Code generated by go-swagger; DO NOT EDIT.

package catalog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/koyeb/koyeb-cli/pkg/kclient/models"
)

// CatalogListCatalogStoresReader is a Reader for the CatalogListCatalogStores structure.
type CatalogListCatalogStoresReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CatalogListCatalogStoresReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCatalogListCatalogStoresOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCatalogListCatalogStoresBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCatalogListCatalogStoresForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCatalogListCatalogStoresNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewCatalogListCatalogStoresDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCatalogListCatalogStoresOK creates a CatalogListCatalogStoresOK with default headers values
func NewCatalogListCatalogStoresOK() *CatalogListCatalogStoresOK {
	return &CatalogListCatalogStoresOK{}
}

/*CatalogListCatalogStoresOK handles this case with default header values.

A successful response.
*/
type CatalogListCatalogStoresOK struct {
	Payload *models.StorageListCatalogStoresReply
}

func (o *CatalogListCatalogStoresOK) Error() string {
	return fmt.Sprintf("[GET /v1/catalog/stores][%d] catalogListCatalogStoresOK  %+v", 200, o.Payload)
}

func (o *CatalogListCatalogStoresOK) GetPayload() *models.StorageListCatalogStoresReply {
	return o.Payload
}

func (o *CatalogListCatalogStoresOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StorageListCatalogStoresReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCatalogListCatalogStoresBadRequest creates a CatalogListCatalogStoresBadRequest with default headers values
func NewCatalogListCatalogStoresBadRequest() *CatalogListCatalogStoresBadRequest {
	return &CatalogListCatalogStoresBadRequest{}
}

/*CatalogListCatalogStoresBadRequest handles this case with default header values.

Validation error
*/
type CatalogListCatalogStoresBadRequest struct {
	Payload *models.CommonErrorWithFields
}

func (o *CatalogListCatalogStoresBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/catalog/stores][%d] catalogListCatalogStoresBadRequest  %+v", 400, o.Payload)
}

func (o *CatalogListCatalogStoresBadRequest) GetPayload() *models.CommonErrorWithFields {
	return o.Payload
}

func (o *CatalogListCatalogStoresBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonErrorWithFields)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCatalogListCatalogStoresForbidden creates a CatalogListCatalogStoresForbidden with default headers values
func NewCatalogListCatalogStoresForbidden() *CatalogListCatalogStoresForbidden {
	return &CatalogListCatalogStoresForbidden{}
}

/*CatalogListCatalogStoresForbidden handles this case with default header values.

Returned when the user does not have permission to access the resource.
*/
type CatalogListCatalogStoresForbidden struct {
	Payload *models.CommonError
}

func (o *CatalogListCatalogStoresForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/catalog/stores][%d] catalogListCatalogStoresForbidden  %+v", 403, o.Payload)
}

func (o *CatalogListCatalogStoresForbidden) GetPayload() *models.CommonError {
	return o.Payload
}

func (o *CatalogListCatalogStoresForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCatalogListCatalogStoresNotFound creates a CatalogListCatalogStoresNotFound with default headers values
func NewCatalogListCatalogStoresNotFound() *CatalogListCatalogStoresNotFound {
	return &CatalogListCatalogStoresNotFound{}
}

/*CatalogListCatalogStoresNotFound handles this case with default header values.

Returned when the resource does not exist.
*/
type CatalogListCatalogStoresNotFound struct {
	Payload *models.CommonError
}

func (o *CatalogListCatalogStoresNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/catalog/stores][%d] catalogListCatalogStoresNotFound  %+v", 404, o.Payload)
}

func (o *CatalogListCatalogStoresNotFound) GetPayload() *models.CommonError {
	return o.Payload
}

func (o *CatalogListCatalogStoresNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCatalogListCatalogStoresDefault creates a CatalogListCatalogStoresDefault with default headers values
func NewCatalogListCatalogStoresDefault(code int) *CatalogListCatalogStoresDefault {
	return &CatalogListCatalogStoresDefault{
		_statusCode: code,
	}
}

/*CatalogListCatalogStoresDefault handles this case with default header values.

An unexpected error response
*/
type CatalogListCatalogStoresDefault struct {
	_statusCode int

	Payload *models.GatewayruntimeError
}

// Code gets the status code for the catalog list catalog stores default response
func (o *CatalogListCatalogStoresDefault) Code() int {
	return o._statusCode
}

func (o *CatalogListCatalogStoresDefault) Error() string {
	return fmt.Sprintf("[GET /v1/catalog/stores][%d] Catalog_ListCatalogStores default  %+v", o._statusCode, o.Payload)
}

func (o *CatalogListCatalogStoresDefault) GetPayload() *models.GatewayruntimeError {
	return o.Payload
}

func (o *CatalogListCatalogStoresDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GatewayruntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
