// Code generated by go-swagger; DO NOT EDIT.

package catalog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCatalogStoreParams creates a new GetCatalogStoreParams object
// with the default values initialized.
func NewGetCatalogStoreParams() *GetCatalogStoreParams {
	var ()
	return &GetCatalogStoreParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCatalogStoreParamsWithTimeout creates a new GetCatalogStoreParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCatalogStoreParamsWithTimeout(timeout time.Duration) *GetCatalogStoreParams {
	var ()
	return &GetCatalogStoreParams{

		timeout: timeout,
	}
}

// NewGetCatalogStoreParamsWithContext creates a new GetCatalogStoreParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCatalogStoreParamsWithContext(ctx context.Context) *GetCatalogStoreParams {
	var ()
	return &GetCatalogStoreParams{

		Context: ctx,
	}
}

// NewGetCatalogStoreParamsWithHTTPClient creates a new GetCatalogStoreParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCatalogStoreParamsWithHTTPClient(client *http.Client) *GetCatalogStoreParams {
	var ()
	return &GetCatalogStoreParams{
		HTTPClient: client,
	}
}

/*GetCatalogStoreParams contains all the parameters to send to the API endpoint
for the get catalog store operation typically these are written to a http.Request
*/
type GetCatalogStoreParams struct {

	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get catalog store params
func (o *GetCatalogStoreParams) WithTimeout(timeout time.Duration) *GetCatalogStoreParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get catalog store params
func (o *GetCatalogStoreParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get catalog store params
func (o *GetCatalogStoreParams) WithContext(ctx context.Context) *GetCatalogStoreParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get catalog store params
func (o *GetCatalogStoreParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get catalog store params
func (o *GetCatalogStoreParams) WithHTTPClient(client *http.Client) *GetCatalogStoreParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get catalog store params
func (o *GetCatalogStoreParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get catalog store params
func (o *GetCatalogStoreParams) WithName(name string) *GetCatalogStoreParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get catalog store params
func (o *GetCatalogStoreParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetCatalogStoreParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
