// Code generated by go-swagger; DO NOT EDIT.

package catalog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCatalogServiceMixin0Params creates a new GetCatalogServiceMixin0Params object
// with the default values initialized.
func NewGetCatalogServiceMixin0Params() *GetCatalogServiceMixin0Params {
	var ()
	return &GetCatalogServiceMixin0Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCatalogServiceMixin0ParamsWithTimeout creates a new GetCatalogServiceMixin0Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCatalogServiceMixin0ParamsWithTimeout(timeout time.Duration) *GetCatalogServiceMixin0Params {
	var ()
	return &GetCatalogServiceMixin0Params{

		timeout: timeout,
	}
}

// NewGetCatalogServiceMixin0ParamsWithContext creates a new GetCatalogServiceMixin0Params object
// with the default values initialized, and the ability to set a context for a request
func NewGetCatalogServiceMixin0ParamsWithContext(ctx context.Context) *GetCatalogServiceMixin0Params {
	var ()
	return &GetCatalogServiceMixin0Params{

		Context: ctx,
	}
}

// NewGetCatalogServiceMixin0ParamsWithHTTPClient creates a new GetCatalogServiceMixin0Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCatalogServiceMixin0ParamsWithHTTPClient(client *http.Client) *GetCatalogServiceMixin0Params {
	var ()
	return &GetCatalogServiceMixin0Params{
		HTTPClient: client,
	}
}

/*GetCatalogServiceMixin0Params contains all the parameters to send to the API endpoint
for the get catalog service mixin0 operation typically these are written to a http.Request
*/
type GetCatalogServiceMixin0Params struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get catalog service mixin0 params
func (o *GetCatalogServiceMixin0Params) WithTimeout(timeout time.Duration) *GetCatalogServiceMixin0Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get catalog service mixin0 params
func (o *GetCatalogServiceMixin0Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get catalog service mixin0 params
func (o *GetCatalogServiceMixin0Params) WithContext(ctx context.Context) *GetCatalogServiceMixin0Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get catalog service mixin0 params
func (o *GetCatalogServiceMixin0Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get catalog service mixin0 params
func (o *GetCatalogServiceMixin0Params) WithHTTPClient(client *http.Client) *GetCatalogServiceMixin0Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get catalog service mixin0 params
func (o *GetCatalogServiceMixin0Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get catalog service mixin0 params
func (o *GetCatalogServiceMixin0Params) WithID(id string) *GetCatalogServiceMixin0Params {
	o.SetID(id)
	return o
}

// SetID adds the id to the get catalog service mixin0 params
func (o *GetCatalogServiceMixin0Params) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetCatalogServiceMixin0Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
