// Code generated by go-swagger; DO NOT EDIT.

package catalog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCatalogIntegrationParams creates a new GetCatalogIntegrationParams object
// with the default values initialized.
func NewGetCatalogIntegrationParams() *GetCatalogIntegrationParams {
	var ()
	return &GetCatalogIntegrationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCatalogIntegrationParamsWithTimeout creates a new GetCatalogIntegrationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCatalogIntegrationParamsWithTimeout(timeout time.Duration) *GetCatalogIntegrationParams {
	var ()
	return &GetCatalogIntegrationParams{

		timeout: timeout,
	}
}

// NewGetCatalogIntegrationParamsWithContext creates a new GetCatalogIntegrationParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCatalogIntegrationParamsWithContext(ctx context.Context) *GetCatalogIntegrationParams {
	var ()
	return &GetCatalogIntegrationParams{

		Context: ctx,
	}
}

// NewGetCatalogIntegrationParamsWithHTTPClient creates a new GetCatalogIntegrationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCatalogIntegrationParamsWithHTTPClient(client *http.Client) *GetCatalogIntegrationParams {
	var ()
	return &GetCatalogIntegrationParams{
		HTTPClient: client,
	}
}

/*GetCatalogIntegrationParams contains all the parameters to send to the API endpoint
for the get catalog integration operation typically these are written to a http.Request
*/
type GetCatalogIntegrationParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get catalog integration params
func (o *GetCatalogIntegrationParams) WithTimeout(timeout time.Duration) *GetCatalogIntegrationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get catalog integration params
func (o *GetCatalogIntegrationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get catalog integration params
func (o *GetCatalogIntegrationParams) WithContext(ctx context.Context) *GetCatalogIntegrationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get catalog integration params
func (o *GetCatalogIntegrationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get catalog integration params
func (o *GetCatalogIntegrationParams) WithHTTPClient(client *http.Client) *GetCatalogIntegrationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get catalog integration params
func (o *GetCatalogIntegrationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get catalog integration params
func (o *GetCatalogIntegrationParams) WithID(id string) *GetCatalogIntegrationParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get catalog integration params
func (o *GetCatalogIntegrationParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetCatalogIntegrationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
