// Code generated by go-swagger; DO NOT EDIT.

package catalog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListCatalogServicesParams creates a new ListCatalogServicesParams object
// with the default values initialized.
func NewListCatalogServicesParams() *ListCatalogServicesParams {
	var ()
	return &ListCatalogServicesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListCatalogServicesParamsWithTimeout creates a new ListCatalogServicesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListCatalogServicesParamsWithTimeout(timeout time.Duration) *ListCatalogServicesParams {
	var ()
	return &ListCatalogServicesParams{

		timeout: timeout,
	}
}

// NewListCatalogServicesParamsWithContext creates a new ListCatalogServicesParams object
// with the default values initialized, and the ability to set a context for a request
func NewListCatalogServicesParamsWithContext(ctx context.Context) *ListCatalogServicesParams {
	var ()
	return &ListCatalogServicesParams{

		Context: ctx,
	}
}

// NewListCatalogServicesParamsWithHTTPClient creates a new ListCatalogServicesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListCatalogServicesParamsWithHTTPClient(client *http.Client) *ListCatalogServicesParams {
	var ()
	return &ListCatalogServicesParams{
		HTTPClient: client,
	}
}

/*ListCatalogServicesParams contains all the parameters to send to the API endpoint
for the list catalog services operation typically these are written to a http.Request
*/
type ListCatalogServicesParams struct {

	/*Limit*/
	Limit *string
	/*Name*/
	Name *string
	/*Offset*/
	Offset *string
	/*Tags*/
	Tags *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list catalog services params
func (o *ListCatalogServicesParams) WithTimeout(timeout time.Duration) *ListCatalogServicesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list catalog services params
func (o *ListCatalogServicesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list catalog services params
func (o *ListCatalogServicesParams) WithContext(ctx context.Context) *ListCatalogServicesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list catalog services params
func (o *ListCatalogServicesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list catalog services params
func (o *ListCatalogServicesParams) WithHTTPClient(client *http.Client) *ListCatalogServicesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list catalog services params
func (o *ListCatalogServicesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the list catalog services params
func (o *ListCatalogServicesParams) WithLimit(limit *string) *ListCatalogServicesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the list catalog services params
func (o *ListCatalogServicesParams) SetLimit(limit *string) {
	o.Limit = limit
}

// WithName adds the name to the list catalog services params
func (o *ListCatalogServicesParams) WithName(name *string) *ListCatalogServicesParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the list catalog services params
func (o *ListCatalogServicesParams) SetName(name *string) {
	o.Name = name
}

// WithOffset adds the offset to the list catalog services params
func (o *ListCatalogServicesParams) WithOffset(offset *string) *ListCatalogServicesParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the list catalog services params
func (o *ListCatalogServicesParams) SetOffset(offset *string) {
	o.Offset = offset
}

// WithTags adds the tags to the list catalog services params
func (o *ListCatalogServicesParams) WithTags(tags *string) *ListCatalogServicesParams {
	o.SetTags(tags)
	return o
}

// SetTags adds the tags to the list catalog services params
func (o *ListCatalogServicesParams) SetTags(tags *string) {
	o.Tags = tags
}

// WriteToRequest writes these params to a swagger request
func (o *ListCatalogServicesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit string
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := qrLimit
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset string
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := qrOffset
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Tags != nil {

		// query param tags
		var qrTags string
		if o.Tags != nil {
			qrTags = *o.Tags
		}
		qTags := qrTags
		if qTags != "" {
			if err := r.SetQueryParam("tags", qTags); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
