// Code generated by go-swagger; DO NOT EDIT.

package catalog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListCatalogStoresParams creates a new ListCatalogStoresParams object
// with the default values initialized.
func NewListCatalogStoresParams() *ListCatalogStoresParams {
	var ()
	return &ListCatalogStoresParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListCatalogStoresParamsWithTimeout creates a new ListCatalogStoresParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListCatalogStoresParamsWithTimeout(timeout time.Duration) *ListCatalogStoresParams {
	var ()
	return &ListCatalogStoresParams{

		timeout: timeout,
	}
}

// NewListCatalogStoresParamsWithContext creates a new ListCatalogStoresParams object
// with the default values initialized, and the ability to set a context for a request
func NewListCatalogStoresParamsWithContext(ctx context.Context) *ListCatalogStoresParams {
	var ()
	return &ListCatalogStoresParams{

		Context: ctx,
	}
}

// NewListCatalogStoresParamsWithHTTPClient creates a new ListCatalogStoresParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListCatalogStoresParamsWithHTTPClient(client *http.Client) *ListCatalogStoresParams {
	var ()
	return &ListCatalogStoresParams{
		HTTPClient: client,
	}
}

/*ListCatalogStoresParams contains all the parameters to send to the API endpoint
for the list catalog stores operation typically these are written to a http.Request
*/
type ListCatalogStoresParams struct {

	/*Limit*/
	Limit *string
	/*Name*/
	Name *string
	/*Offset*/
	Offset *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list catalog stores params
func (o *ListCatalogStoresParams) WithTimeout(timeout time.Duration) *ListCatalogStoresParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list catalog stores params
func (o *ListCatalogStoresParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list catalog stores params
func (o *ListCatalogStoresParams) WithContext(ctx context.Context) *ListCatalogStoresParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list catalog stores params
func (o *ListCatalogStoresParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list catalog stores params
func (o *ListCatalogStoresParams) WithHTTPClient(client *http.Client) *ListCatalogStoresParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list catalog stores params
func (o *ListCatalogStoresParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the list catalog stores params
func (o *ListCatalogStoresParams) WithLimit(limit *string) *ListCatalogStoresParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the list catalog stores params
func (o *ListCatalogStoresParams) SetLimit(limit *string) {
	o.Limit = limit
}

// WithName adds the name to the list catalog stores params
func (o *ListCatalogStoresParams) WithName(name *string) *ListCatalogStoresParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the list catalog stores params
func (o *ListCatalogStoresParams) SetName(name *string) {
	o.Name = name
}

// WithOffset adds the offset to the list catalog stores params
func (o *ListCatalogStoresParams) WithOffset(offset *string) *ListCatalogStoresParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the list catalog stores params
func (o *ListCatalogStoresParams) SetOffset(offset *string) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *ListCatalogStoresParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit string
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := qrLimit
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset string
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := qrOffset
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
