// Code generated by go-swagger; DO NOT EDIT.

package public_catalog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/koyeb/koyeb-cli/pkg/kclient/models"
)

// ListCatalogIntegrationsReader is a Reader for the ListCatalogIntegrations structure.
type ListCatalogIntegrationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListCatalogIntegrationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListCatalogIntegrationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListCatalogIntegrationsOK creates a ListCatalogIntegrationsOK with default headers values
func NewListCatalogIntegrationsOK() *ListCatalogIntegrationsOK {
	return &ListCatalogIntegrationsOK{}
}

/*ListCatalogIntegrationsOK handles this case with default header values.

A successful response.
*/
type ListCatalogIntegrationsOK struct {
	Payload *models.StorageListCatalogIntegrationsReply
}

func (o *ListCatalogIntegrationsOK) Error() string {
	return fmt.Sprintf("[GET /v1/public/catalog/integrations][%d] listCatalogIntegrationsOK  %+v", 200, o.Payload)
}

func (o *ListCatalogIntegrationsOK) GetPayload() *models.StorageListCatalogIntegrationsReply {
	return o.Payload
}

func (o *ListCatalogIntegrationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StorageListCatalogIntegrationsReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
