// Code generated by go-swagger; DO NOT EDIT.

package credentials

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/koyeb/koyeb-cli/pkg/kclient/models"
)

// NewCredentialsUpdateCredentialParams creates a new CredentialsUpdateCredentialParams object
// with the default values initialized.
func NewCredentialsUpdateCredentialParams() *CredentialsUpdateCredentialParams {
	var ()
	return &CredentialsUpdateCredentialParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCredentialsUpdateCredentialParamsWithTimeout creates a new CredentialsUpdateCredentialParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCredentialsUpdateCredentialParamsWithTimeout(timeout time.Duration) *CredentialsUpdateCredentialParams {
	var ()
	return &CredentialsUpdateCredentialParams{

		timeout: timeout,
	}
}

// NewCredentialsUpdateCredentialParamsWithContext creates a new CredentialsUpdateCredentialParams object
// with the default values initialized, and the ability to set a context for a request
func NewCredentialsUpdateCredentialParamsWithContext(ctx context.Context) *CredentialsUpdateCredentialParams {
	var ()
	return &CredentialsUpdateCredentialParams{

		Context: ctx,
	}
}

// NewCredentialsUpdateCredentialParamsWithHTTPClient creates a new CredentialsUpdateCredentialParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCredentialsUpdateCredentialParamsWithHTTPClient(client *http.Client) *CredentialsUpdateCredentialParams {
	var ()
	return &CredentialsUpdateCredentialParams{
		HTTPClient: client,
	}
}

/*CredentialsUpdateCredentialParams contains all the parameters to send to the API endpoint
for the credentials update credential operation typically these are written to a http.Request
*/
type CredentialsUpdateCredentialParams struct {

	/*Body*/
	Body *models.AccountCredential
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the credentials update credential params
func (o *CredentialsUpdateCredentialParams) WithTimeout(timeout time.Duration) *CredentialsUpdateCredentialParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the credentials update credential params
func (o *CredentialsUpdateCredentialParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the credentials update credential params
func (o *CredentialsUpdateCredentialParams) WithContext(ctx context.Context) *CredentialsUpdateCredentialParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the credentials update credential params
func (o *CredentialsUpdateCredentialParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the credentials update credential params
func (o *CredentialsUpdateCredentialParams) WithHTTPClient(client *http.Client) *CredentialsUpdateCredentialParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the credentials update credential params
func (o *CredentialsUpdateCredentialParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the credentials update credential params
func (o *CredentialsUpdateCredentialParams) WithBody(body *models.AccountCredential) *CredentialsUpdateCredentialParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the credentials update credential params
func (o *CredentialsUpdateCredentialParams) SetBody(body *models.AccountCredential) {
	o.Body = body
}

// WithID adds the id to the credentials update credential params
func (o *CredentialsUpdateCredentialParams) WithID(id string) *CredentialsUpdateCredentialParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the credentials update credential params
func (o *CredentialsUpdateCredentialParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CredentialsUpdateCredentialParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
