// Code generated by go-swagger; DO NOT EDIT.

package credentials

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/koyeb/koyeb-cli/pkg/kclient/models"
)

// CredentialsDeleteCredentialReader is a Reader for the CredentialsDeleteCredential structure.
type CredentialsDeleteCredentialReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CredentialsDeleteCredentialReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCredentialsDeleteCredentialOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCredentialsDeleteCredentialBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCredentialsDeleteCredentialForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCredentialsDeleteCredentialNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewCredentialsDeleteCredentialDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCredentialsDeleteCredentialOK creates a CredentialsDeleteCredentialOK with default headers values
func NewCredentialsDeleteCredentialOK() *CredentialsDeleteCredentialOK {
	return &CredentialsDeleteCredentialOK{}
}

/*CredentialsDeleteCredentialOK handles this case with default header values.

A successful response.
*/
type CredentialsDeleteCredentialOK struct {
	Payload models.CommonEmpty
}

func (o *CredentialsDeleteCredentialOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/credentials/{id}][%d] credentialsDeleteCredentialOK  %+v", 200, o.Payload)
}

func (o *CredentialsDeleteCredentialOK) GetPayload() models.CommonEmpty {
	return o.Payload
}

func (o *CredentialsDeleteCredentialOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCredentialsDeleteCredentialBadRequest creates a CredentialsDeleteCredentialBadRequest with default headers values
func NewCredentialsDeleteCredentialBadRequest() *CredentialsDeleteCredentialBadRequest {
	return &CredentialsDeleteCredentialBadRequest{}
}

/*CredentialsDeleteCredentialBadRequest handles this case with default header values.

Validation error
*/
type CredentialsDeleteCredentialBadRequest struct {
	Payload *models.CommonErrorWithFields
}

func (o *CredentialsDeleteCredentialBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /v1/credentials/{id}][%d] credentialsDeleteCredentialBadRequest  %+v", 400, o.Payload)
}

func (o *CredentialsDeleteCredentialBadRequest) GetPayload() *models.CommonErrorWithFields {
	return o.Payload
}

func (o *CredentialsDeleteCredentialBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonErrorWithFields)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCredentialsDeleteCredentialForbidden creates a CredentialsDeleteCredentialForbidden with default headers values
func NewCredentialsDeleteCredentialForbidden() *CredentialsDeleteCredentialForbidden {
	return &CredentialsDeleteCredentialForbidden{}
}

/*CredentialsDeleteCredentialForbidden handles this case with default header values.

Returned when the user does not have permission to access the resource.
*/
type CredentialsDeleteCredentialForbidden struct {
	Payload *models.CommonError
}

func (o *CredentialsDeleteCredentialForbidden) Error() string {
	return fmt.Sprintf("[DELETE /v1/credentials/{id}][%d] credentialsDeleteCredentialForbidden  %+v", 403, o.Payload)
}

func (o *CredentialsDeleteCredentialForbidden) GetPayload() *models.CommonError {
	return o.Payload
}

func (o *CredentialsDeleteCredentialForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCredentialsDeleteCredentialNotFound creates a CredentialsDeleteCredentialNotFound with default headers values
func NewCredentialsDeleteCredentialNotFound() *CredentialsDeleteCredentialNotFound {
	return &CredentialsDeleteCredentialNotFound{}
}

/*CredentialsDeleteCredentialNotFound handles this case with default header values.

Returned when the resource does not exist.
*/
type CredentialsDeleteCredentialNotFound struct {
	Payload *models.CommonError
}

func (o *CredentialsDeleteCredentialNotFound) Error() string {
	return fmt.Sprintf("[DELETE /v1/credentials/{id}][%d] credentialsDeleteCredentialNotFound  %+v", 404, o.Payload)
}

func (o *CredentialsDeleteCredentialNotFound) GetPayload() *models.CommonError {
	return o.Payload
}

func (o *CredentialsDeleteCredentialNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCredentialsDeleteCredentialDefault creates a CredentialsDeleteCredentialDefault with default headers values
func NewCredentialsDeleteCredentialDefault(code int) *CredentialsDeleteCredentialDefault {
	return &CredentialsDeleteCredentialDefault{
		_statusCode: code,
	}
}

/*CredentialsDeleteCredentialDefault handles this case with default header values.

An unexpected error response
*/
type CredentialsDeleteCredentialDefault struct {
	_statusCode int

	Payload *models.GatewayruntimeError
}

// Code gets the status code for the credentials delete credential default response
func (o *CredentialsDeleteCredentialDefault) Code() int {
	return o._statusCode
}

func (o *CredentialsDeleteCredentialDefault) Error() string {
	return fmt.Sprintf("[DELETE /v1/credentials/{id}][%d] credentials_DeleteCredential default  %+v", o._statusCode, o.Payload)
}

func (o *CredentialsDeleteCredentialDefault) GetPayload() *models.GatewayruntimeError {
	return o.Payload
}

func (o *CredentialsDeleteCredentialDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GatewayruntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
