// Code generated by go-swagger; DO NOT EDIT.

package credentials

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/koyeb/koyeb-cli/pkg/kclient/models"
)

// CredentialsGetCredentialReader is a Reader for the CredentialsGetCredential structure.
type CredentialsGetCredentialReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CredentialsGetCredentialReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCredentialsGetCredentialOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCredentialsGetCredentialBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCredentialsGetCredentialForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCredentialsGetCredentialNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewCredentialsGetCredentialDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCredentialsGetCredentialOK creates a CredentialsGetCredentialOK with default headers values
func NewCredentialsGetCredentialOK() *CredentialsGetCredentialOK {
	return &CredentialsGetCredentialOK{}
}

/*CredentialsGetCredentialOK handles this case with default header values.

A successful response.
*/
type CredentialsGetCredentialOK struct {
	Payload *models.AccountCredentialReply
}

func (o *CredentialsGetCredentialOK) Error() string {
	return fmt.Sprintf("[GET /v1/credentials/{id}][%d] credentialsGetCredentialOK  %+v", 200, o.Payload)
}

func (o *CredentialsGetCredentialOK) GetPayload() *models.AccountCredentialReply {
	return o.Payload
}

func (o *CredentialsGetCredentialOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AccountCredentialReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCredentialsGetCredentialBadRequest creates a CredentialsGetCredentialBadRequest with default headers values
func NewCredentialsGetCredentialBadRequest() *CredentialsGetCredentialBadRequest {
	return &CredentialsGetCredentialBadRequest{}
}

/*CredentialsGetCredentialBadRequest handles this case with default header values.

Validation error
*/
type CredentialsGetCredentialBadRequest struct {
	Payload *models.CommonErrorWithFields
}

func (o *CredentialsGetCredentialBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/credentials/{id}][%d] credentialsGetCredentialBadRequest  %+v", 400, o.Payload)
}

func (o *CredentialsGetCredentialBadRequest) GetPayload() *models.CommonErrorWithFields {
	return o.Payload
}

func (o *CredentialsGetCredentialBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonErrorWithFields)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCredentialsGetCredentialForbidden creates a CredentialsGetCredentialForbidden with default headers values
func NewCredentialsGetCredentialForbidden() *CredentialsGetCredentialForbidden {
	return &CredentialsGetCredentialForbidden{}
}

/*CredentialsGetCredentialForbidden handles this case with default header values.

Returned when the user does not have permission to access the resource.
*/
type CredentialsGetCredentialForbidden struct {
	Payload *models.CommonError
}

func (o *CredentialsGetCredentialForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/credentials/{id}][%d] credentialsGetCredentialForbidden  %+v", 403, o.Payload)
}

func (o *CredentialsGetCredentialForbidden) GetPayload() *models.CommonError {
	return o.Payload
}

func (o *CredentialsGetCredentialForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCredentialsGetCredentialNotFound creates a CredentialsGetCredentialNotFound with default headers values
func NewCredentialsGetCredentialNotFound() *CredentialsGetCredentialNotFound {
	return &CredentialsGetCredentialNotFound{}
}

/*CredentialsGetCredentialNotFound handles this case with default header values.

Returned when the resource does not exist.
*/
type CredentialsGetCredentialNotFound struct {
	Payload *models.CommonError
}

func (o *CredentialsGetCredentialNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/credentials/{id}][%d] credentialsGetCredentialNotFound  %+v", 404, o.Payload)
}

func (o *CredentialsGetCredentialNotFound) GetPayload() *models.CommonError {
	return o.Payload
}

func (o *CredentialsGetCredentialNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCredentialsGetCredentialDefault creates a CredentialsGetCredentialDefault with default headers values
func NewCredentialsGetCredentialDefault(code int) *CredentialsGetCredentialDefault {
	return &CredentialsGetCredentialDefault{
		_statusCode: code,
	}
}

/*CredentialsGetCredentialDefault handles this case with default header values.

An unexpected error response
*/
type CredentialsGetCredentialDefault struct {
	_statusCode int

	Payload *models.GatewayruntimeError
}

// Code gets the status code for the credentials get credential default response
func (o *CredentialsGetCredentialDefault) Code() int {
	return o._statusCode
}

func (o *CredentialsGetCredentialDefault) Error() string {
	return fmt.Sprintf("[GET /v1/credentials/{id}][%d] credentials_GetCredential default  %+v", o._statusCode, o.Payload)
}

func (o *CredentialsGetCredentialDefault) GetPayload() *models.GatewayruntimeError {
	return o.Payload
}

func (o *CredentialsGetCredentialDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GatewayruntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
