// Code generated by go-swagger; DO NOT EDIT.

package stores

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetStoreParams creates a new GetStoreParams object
// with the default values initialized.
func NewGetStoreParams() *GetStoreParams {
	var ()
	return &GetStoreParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetStoreParamsWithTimeout creates a new GetStoreParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetStoreParamsWithTimeout(timeout time.Duration) *GetStoreParams {
	var ()
	return &GetStoreParams{

		timeout: timeout,
	}
}

// NewGetStoreParamsWithContext creates a new GetStoreParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetStoreParamsWithContext(ctx context.Context) *GetStoreParams {
	var ()
	return &GetStoreParams{

		Context: ctx,
	}
}

// NewGetStoreParamsWithHTTPClient creates a new GetStoreParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetStoreParamsWithHTTPClient(client *http.Client) *GetStoreParams {
	var ()
	return &GetStoreParams{
		HTTPClient: client,
	}
}

/*GetStoreParams contains all the parameters to send to the API endpoint
for the get store operation typically these are written to a http.Request
*/
type GetStoreParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get store params
func (o *GetStoreParams) WithTimeout(timeout time.Duration) *GetStoreParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get store params
func (o *GetStoreParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get store params
func (o *GetStoreParams) WithContext(ctx context.Context) *GetStoreParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get store params
func (o *GetStoreParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get store params
func (o *GetStoreParams) WithHTTPClient(client *http.Client) *GetStoreParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get store params
func (o *GetStoreParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get store params
func (o *GetStoreParams) WithID(id string) *GetStoreParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get store params
func (o *GetStoreParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetStoreParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
