// Code generated by go-swagger; DO NOT EDIT.

package stores

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListStoresParams creates a new ListStoresParams object
// with the default values initialized.
func NewListStoresParams() *ListStoresParams {
	var ()
	return &ListStoresParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListStoresParamsWithTimeout creates a new ListStoresParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListStoresParamsWithTimeout(timeout time.Duration) *ListStoresParams {
	var ()
	return &ListStoresParams{

		timeout: timeout,
	}
}

// NewListStoresParamsWithContext creates a new ListStoresParams object
// with the default values initialized, and the ability to set a context for a request
func NewListStoresParamsWithContext(ctx context.Context) *ListStoresParams {
	var ()
	return &ListStoresParams{

		Context: ctx,
	}
}

// NewListStoresParamsWithHTTPClient creates a new ListStoresParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListStoresParamsWithHTTPClient(client *http.Client) *ListStoresParams {
	var ()
	return &ListStoresParams{
		HTTPClient: client,
	}
}

/*ListStoresParams contains all the parameters to send to the API endpoint
for the list stores operation typically these are written to a http.Request
*/
type ListStoresParams struct {

	/*Limit*/
	Limit *string
	/*Name*/
	Name *string
	/*Offset*/
	Offset *string
	/*Status*/
	Status *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list stores params
func (o *ListStoresParams) WithTimeout(timeout time.Duration) *ListStoresParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list stores params
func (o *ListStoresParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list stores params
func (o *ListStoresParams) WithContext(ctx context.Context) *ListStoresParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list stores params
func (o *ListStoresParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list stores params
func (o *ListStoresParams) WithHTTPClient(client *http.Client) *ListStoresParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list stores params
func (o *ListStoresParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the list stores params
func (o *ListStoresParams) WithLimit(limit *string) *ListStoresParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the list stores params
func (o *ListStoresParams) SetLimit(limit *string) {
	o.Limit = limit
}

// WithName adds the name to the list stores params
func (o *ListStoresParams) WithName(name *string) *ListStoresParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the list stores params
func (o *ListStoresParams) SetName(name *string) {
	o.Name = name
}

// WithOffset adds the offset to the list stores params
func (o *ListStoresParams) WithOffset(offset *string) *ListStoresParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the list stores params
func (o *ListStoresParams) SetOffset(offset *string) {
	o.Offset = offset
}

// WithStatus adds the status to the list stores params
func (o *ListStoresParams) WithStatus(status *string) *ListStoresParams {
	o.SetStatus(status)
	return o
}

// SetStatus adds the status to the list stores params
func (o *ListStoresParams) SetStatus(status *string) {
	o.Status = status
}

// WriteToRequest writes these params to a swagger request
func (o *ListStoresParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit string
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := qrLimit
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset string
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := qrOffset
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Status != nil {

		// query param status
		var qrStatus string
		if o.Status != nil {
			qrStatus = *o.Status
		}
		qStatus := qrStatus
		if qStatus != "" {
			if err := r.SetQueryParam("status", qStatus); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
