// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StorageStackObjectExecutionReply storage stack object execution reply
// swagger:model storageStackObjectExecutionReply
type StorageStackObjectExecutionReply struct {

	// object execution
	ObjectExecution *StorageStackObjectExecutionBody `json:"object_execution,omitempty"`
}

// Validate validates this storage stack object execution reply
func (m *StorageStackObjectExecutionReply) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateObjectExecution(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StorageStackObjectExecutionReply) validateObjectExecution(formats strfmt.Registry) error {

	if swag.IsZero(m.ObjectExecution) { // not required
		return nil
	}

	if m.ObjectExecution != nil {
		if err := m.ObjectExecution.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("object_execution")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *StorageStackObjectExecutionReply) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StorageStackObjectExecutionReply) UnmarshalBinary(b []byte) error {
	var res StorageStackObjectExecutionReply
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
