// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StorageStackObjectExecutionsReply storage stack object executions reply
// swagger:model storageStackObjectExecutionsReply
type StorageStackObjectExecutionsReply struct {

	// count
	Count int64 `json:"count,omitempty"`

	// limit
	Limit int64 `json:"limit,omitempty"`

	// object executions
	ObjectExecutions []*StorageStackObjectExecutionBody `json:"object_executions"`

	// offset
	Offset int64 `json:"offset,omitempty"`
}

// Validate validates this storage stack object executions reply
func (m *StorageStackObjectExecutionsReply) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateObjectExecutions(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StorageStackObjectExecutionsReply) validateObjectExecutions(formats strfmt.Registry) error {

	if swag.IsZero(m.ObjectExecutions) { // not required
		return nil
	}

	for i := 0; i < len(m.ObjectExecutions); i++ {
		if swag.IsZero(m.ObjectExecutions[i]) { // not required
			continue
		}

		if m.ObjectExecutions[i] != nil {
			if err := m.ObjectExecutions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("object_executions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *StorageStackObjectExecutionsReply) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StorageStackObjectExecutionsReply) UnmarshalBinary(b []byte) error {
	var res StorageStackObjectExecutionsReply
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
