// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// StorageStackRevisionStatus - ERROR: An error happened when deploying the new revision
//  - VALIDATION_ERROR: Indicate that the revision was not valid
// swagger:model storageStackRevisionStatus
type StorageStackRevisionStatus string

const (

	// StorageStackRevisionStatusUNKNOWN captures enum value "UNKNOWN"
	StorageStackRevisionStatusUNKNOWN StorageStackRevisionStatus = "UNKNOWN"

	// StorageStackRevisionStatusUNAVAILABLE captures enum value "UNAVAILABLE"
	StorageStackRevisionStatusUNAVAILABLE StorageStackRevisionStatus = "UNAVAILABLE"

	// StorageStackRevisionStatusPROVISIONING captures enum value "PROVISIONING"
	StorageStackRevisionStatusPROVISIONING StorageStackRevisionStatus = "PROVISIONING"

	// StorageStackRevisionStatusSTOPPING captures enum value "STOPPING"
	StorageStackRevisionStatusSTOPPING StorageStackRevisionStatus = "STOPPING"

	// StorageStackRevisionStatusERROR captures enum value "ERROR"
	StorageStackRevisionStatusERROR StorageStackRevisionStatus = "ERROR"

	// StorageStackRevisionStatusACTIVE captures enum value "ACTIVE"
	StorageStackRevisionStatusACTIVE StorageStackRevisionStatus = "ACTIVE"

	// StorageStackRevisionStatusVALIDATIONERROR captures enum value "VALIDATION_ERROR"
	StorageStackRevisionStatusVALIDATIONERROR StorageStackRevisionStatus = "VALIDATION_ERROR"
)

// for schema
var storageStackRevisionStatusEnum []interface{}

func init() {
	var res []StorageStackRevisionStatus
	if err := json.Unmarshal([]byte(`["UNKNOWN","UNAVAILABLE","PROVISIONING","STOPPING","ERROR","ACTIVE","VALIDATION_ERROR"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		storageStackRevisionStatusEnum = append(storageStackRevisionStatusEnum, v)
	}
}

func (m StorageStackRevisionStatus) validateStorageStackRevisionStatusEnum(path, location string, value StorageStackRevisionStatus) error {
	if err := validate.Enum(path, location, value, storageStackRevisionStatusEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this storage stack revision status
func (m StorageStackRevisionStatus) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateStorageStackRevisionStatusEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
