// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StorageCommitInfo storage commit info
// swagger:model storageCommitInfo
type StorageCommitInfo struct {

	// avatar url
	AvatarURL string `json:"avatar_url,omitempty"`

	// hash
	Hash string `json:"hash,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// user
	User string `json:"user,omitempty"`
}

// Validate validates this storage commit info
func (m *StorageCommitInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StorageCommitInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StorageCommitInfo) UnmarshalBinary(b []byte) error {
	var res StorageCommitInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
