// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StorageNewStackEventReply storage new stack event reply
// swagger:model storageNewStackEventReply
type StorageNewStackEventReply struct {

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this storage new stack event reply
func (m *StorageNewStackEventReply) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StorageNewStackEventReply) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StorageNewStackEventReply) UnmarshalBinary(b []byte) error {
	var res StorageNewStackEventReply
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
