// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StorageDeliveryReply storage delivery reply
// swagger:model storageDeliveryReply
type StorageDeliveryReply struct {

	// delivery
	Delivery *StorageDeliveryBody `json:"delivery,omitempty"`
}

// Validate validates this storage delivery reply
func (m *StorageDeliveryReply) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDelivery(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StorageDeliveryReply) validateDelivery(formats strfmt.Registry) error {

	if swag.IsZero(m.Delivery) { // not required
		return nil
	}

	if m.Delivery != nil {
		if err := m.Delivery.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("delivery")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *StorageDeliveryReply) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StorageDeliveryReply) UnmarshalBinary(b []byte) error {
	var res StorageDeliveryReply
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
