// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StorageManagedStoreReply storage managed store reply
// swagger:model storageManagedStoreReply
type StorageManagedStoreReply struct {

	// managed store
	ManagedStore *StorageManagedStoreBody `json:"managed_store,omitempty"`
}

// Validate validates this storage managed store reply
func (m *StorageManagedStoreReply) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateManagedStore(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StorageManagedStoreReply) validateManagedStore(formats strfmt.Registry) error {

	if swag.IsZero(m.ManagedStore) { // not required
		return nil
	}

	if m.ManagedStore != nil {
		if err := m.ManagedStore.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("managed_store")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *StorageManagedStoreReply) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StorageManagedStoreReply) UnmarshalBinary(b []byte) error {
	var res StorageManagedStoreReply
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
