// Code generated by go-swagger; DO NOT EDIT.

package s3_credentials

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/koyeb/koyeb-cli/pkg/kclient/models"
)

// DeleteS3CredentialReader is a Reader for the DeleteS3Credential structure.
type DeleteS3CredentialReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteS3CredentialReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteS3CredentialOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteS3CredentialOK creates a DeleteS3CredentialOK with default headers values
func NewDeleteS3CredentialOK() *DeleteS3CredentialOK {
	return &DeleteS3CredentialOK{}
}

/*DeleteS3CredentialOK handles this case with default header values.

A successful response.
*/
type DeleteS3CredentialOK struct {
	Payload models.CommonEmpty
}

func (o *DeleteS3CredentialOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/s3_credentials/{id}][%d] deleteS3CredentialOK  %+v", 200, o.Payload)
}

func (o *DeleteS3CredentialOK) GetPayload() models.CommonEmpty {
	return o.Payload
}

func (o *DeleteS3CredentialOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
