// Code generated by go-swagger; DO NOT EDIT.

package stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDisableStackParams creates a new DisableStackParams object
// with the default values initialized.
func NewDisableStackParams() *DisableStackParams {
	var ()
	return &DisableStackParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDisableStackParamsWithTimeout creates a new DisableStackParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDisableStackParamsWithTimeout(timeout time.Duration) *DisableStackParams {
	var ()
	return &DisableStackParams{

		timeout: timeout,
	}
}

// NewDisableStackParamsWithContext creates a new DisableStackParams object
// with the default values initialized, and the ability to set a context for a request
func NewDisableStackParamsWithContext(ctx context.Context) *DisableStackParams {
	var ()
	return &DisableStackParams{

		Context: ctx,
	}
}

// NewDisableStackParamsWithHTTPClient creates a new DisableStackParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDisableStackParamsWithHTTPClient(client *http.Client) *DisableStackParams {
	var ()
	return &DisableStackParams{
		HTTPClient: client,
	}
}

/*DisableStackParams contains all the parameters to send to the API endpoint
for the disable stack operation typically these are written to a http.Request
*/
type DisableStackParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the disable stack params
func (o *DisableStackParams) WithTimeout(timeout time.Duration) *DisableStackParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the disable stack params
func (o *DisableStackParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the disable stack params
func (o *DisableStackParams) WithContext(ctx context.Context) *DisableStackParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the disable stack params
func (o *DisableStackParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the disable stack params
func (o *DisableStackParams) WithHTTPClient(client *http.Client) *DisableStackParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the disable stack params
func (o *DisableStackParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the disable stack params
func (o *DisableStackParams) WithID(id string) *DisableStackParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the disable stack params
func (o *DisableStackParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DisableStackParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
