// Code generated by go-swagger; DO NOT EDIT.

package stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEnableStackWorkflowParams creates a new EnableStackWorkflowParams object
// with the default values initialized.
func NewEnableStackWorkflowParams() *EnableStackWorkflowParams {
	var ()
	return &EnableStackWorkflowParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEnableStackWorkflowParamsWithTimeout creates a new EnableStackWorkflowParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEnableStackWorkflowParamsWithTimeout(timeout time.Duration) *EnableStackWorkflowParams {
	var ()
	return &EnableStackWorkflowParams{

		timeout: timeout,
	}
}

// NewEnableStackWorkflowParamsWithContext creates a new EnableStackWorkflowParams object
// with the default values initialized, and the ability to set a context for a request
func NewEnableStackWorkflowParamsWithContext(ctx context.Context) *EnableStackWorkflowParams {
	var ()
	return &EnableStackWorkflowParams{

		Context: ctx,
	}
}

// NewEnableStackWorkflowParamsWithHTTPClient creates a new EnableStackWorkflowParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEnableStackWorkflowParamsWithHTTPClient(client *http.Client) *EnableStackWorkflowParams {
	var ()
	return &EnableStackWorkflowParams{
		HTTPClient: client,
	}
}

/*EnableStackWorkflowParams contains all the parameters to send to the API endpoint
for the enable stack workflow operation typically these are written to a http.Request
*/
type EnableStackWorkflowParams struct {

	/*ID*/
	ID string
	/*StackID*/
	StackID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the enable stack workflow params
func (o *EnableStackWorkflowParams) WithTimeout(timeout time.Duration) *EnableStackWorkflowParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the enable stack workflow params
func (o *EnableStackWorkflowParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the enable stack workflow params
func (o *EnableStackWorkflowParams) WithContext(ctx context.Context) *EnableStackWorkflowParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the enable stack workflow params
func (o *EnableStackWorkflowParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the enable stack workflow params
func (o *EnableStackWorkflowParams) WithHTTPClient(client *http.Client) *EnableStackWorkflowParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the enable stack workflow params
func (o *EnableStackWorkflowParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the enable stack workflow params
func (o *EnableStackWorkflowParams) WithID(id string) *EnableStackWorkflowParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the enable stack workflow params
func (o *EnableStackWorkflowParams) SetID(id string) {
	o.ID = id
}

// WithStackID adds the stackID to the enable stack workflow params
func (o *EnableStackWorkflowParams) WithStackID(stackID string) *EnableStackWorkflowParams {
	o.SetStackID(stackID)
	return o
}

// SetStackID adds the stackId to the enable stack workflow params
func (o *EnableStackWorkflowParams) SetStackID(stackID string) {
	o.StackID = stackID
}

// WriteToRequest writes these params to a swagger request
func (o *EnableStackWorkflowParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param stack_id
	if err := r.SetPathParam("stack_id", o.StackID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
