// Code generated by go-swagger; DO NOT EDIT.

package stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetStackSourceStatsParams creates a new GetStackSourceStatsParams object
// with the default values initialized.
func NewGetStackSourceStatsParams() *GetStackSourceStatsParams {
	var ()
	return &GetStackSourceStatsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetStackSourceStatsParamsWithTimeout creates a new GetStackSourceStatsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetStackSourceStatsParamsWithTimeout(timeout time.Duration) *GetStackSourceStatsParams {
	var ()
	return &GetStackSourceStatsParams{

		timeout: timeout,
	}
}

// NewGetStackSourceStatsParamsWithContext creates a new GetStackSourceStatsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetStackSourceStatsParamsWithContext(ctx context.Context) *GetStackSourceStatsParams {
	var ()
	return &GetStackSourceStatsParams{

		Context: ctx,
	}
}

// NewGetStackSourceStatsParamsWithHTTPClient creates a new GetStackSourceStatsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetStackSourceStatsParamsWithHTTPClient(client *http.Client) *GetStackSourceStatsParams {
	var ()
	return &GetStackSourceStatsParams{
		HTTPClient: client,
	}
}

/*GetStackSourceStatsParams contains all the parameters to send to the API endpoint
for the get stack source stats operation typically these are written to a http.Request
*/
type GetStackSourceStatsParams struct {

	/*ID*/
	ID string
	/*StackID*/
	StackID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get stack source stats params
func (o *GetStackSourceStatsParams) WithTimeout(timeout time.Duration) *GetStackSourceStatsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get stack source stats params
func (o *GetStackSourceStatsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get stack source stats params
func (o *GetStackSourceStatsParams) WithContext(ctx context.Context) *GetStackSourceStatsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get stack source stats params
func (o *GetStackSourceStatsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get stack source stats params
func (o *GetStackSourceStatsParams) WithHTTPClient(client *http.Client) *GetStackSourceStatsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get stack source stats params
func (o *GetStackSourceStatsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get stack source stats params
func (o *GetStackSourceStatsParams) WithID(id string) *GetStackSourceStatsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get stack source stats params
func (o *GetStackSourceStatsParams) SetID(id string) {
	o.ID = id
}

// WithStackID adds the stackID to the get stack source stats params
func (o *GetStackSourceStatsParams) WithStackID(stackID string) *GetStackSourceStatsParams {
	o.SetStackID(stackID)
	return o
}

// SetStackID adds the stackId to the get stack source stats params
func (o *GetStackSourceStatsParams) SetStackID(stackID string) {
	o.StackID = stackID
}

// WriteToRequest writes these params to a swagger request
func (o *GetStackSourceStatsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param stack_id
	if err := r.SetPathParam("stack_id", o.StackID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
