// Code generated by go-swagger; DO NOT EDIT.

package stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/koyeb/koyeb-cli/pkg/kclient/models"
)

// ListStackEventsReader is a Reader for the ListStackEvents structure.
type ListStackEventsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListStackEventsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListStackEventsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListStackEventsOK creates a ListStackEventsOK with default headers values
func NewListStackEventsOK() *ListStackEventsOK {
	return &ListStackEventsOK{}
}

/*ListStackEventsOK handles this case with default header values.

A successful response.
*/
type ListStackEventsOK struct {
	Payload *models.ActivityActivityFeedReply
}

func (o *ListStackEventsOK) Error() string {
	return fmt.Sprintf("[GET /v1/stacks/{id}/events][%d] listStackEventsOK  %+v", 200, o.Payload)
}

func (o *ListStackEventsOK) GetPayload() *models.ActivityActivityFeedReply {
	return o.Payload
}

func (o *ListStackEventsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ActivityActivityFeedReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
