// Code generated by go-swagger; DO NOT EDIT.

package stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListStackSourcesParams creates a new ListStackSourcesParams object
// with the default values initialized.
func NewListStackSourcesParams() *ListStackSourcesParams {
	var ()
	return &ListStackSourcesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListStackSourcesParamsWithTimeout creates a new ListStackSourcesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListStackSourcesParamsWithTimeout(timeout time.Duration) *ListStackSourcesParams {
	var ()
	return &ListStackSourcesParams{

		timeout: timeout,
	}
}

// NewListStackSourcesParamsWithContext creates a new ListStackSourcesParams object
// with the default values initialized, and the ability to set a context for a request
func NewListStackSourcesParamsWithContext(ctx context.Context) *ListStackSourcesParams {
	var ()
	return &ListStackSourcesParams{

		Context: ctx,
	}
}

// NewListStackSourcesParamsWithHTTPClient creates a new ListStackSourcesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListStackSourcesParamsWithHTTPClient(client *http.Client) *ListStackSourcesParams {
	var ()
	return &ListStackSourcesParams{
		HTTPClient: client,
	}
}

/*ListStackSourcesParams contains all the parameters to send to the API endpoint
for the list stack sources operation typically these are written to a http.Request
*/
type ListStackSourcesParams struct {

	/*ID*/
	ID string
	/*Limit*/
	Limit *string
	/*Offset*/
	Offset *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list stack sources params
func (o *ListStackSourcesParams) WithTimeout(timeout time.Duration) *ListStackSourcesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list stack sources params
func (o *ListStackSourcesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list stack sources params
func (o *ListStackSourcesParams) WithContext(ctx context.Context) *ListStackSourcesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list stack sources params
func (o *ListStackSourcesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list stack sources params
func (o *ListStackSourcesParams) WithHTTPClient(client *http.Client) *ListStackSourcesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list stack sources params
func (o *ListStackSourcesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the list stack sources params
func (o *ListStackSourcesParams) WithID(id string) *ListStackSourcesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the list stack sources params
func (o *ListStackSourcesParams) SetID(id string) {
	o.ID = id
}

// WithLimit adds the limit to the list stack sources params
func (o *ListStackSourcesParams) WithLimit(limit *string) *ListStackSourcesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the list stack sources params
func (o *ListStackSourcesParams) SetLimit(limit *string) {
	o.Limit = limit
}

// WithOffset adds the offset to the list stack sources params
func (o *ListStackSourcesParams) WithOffset(offset *string) *ListStackSourcesParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the list stack sources params
func (o *ListStackSourcesParams) SetOffset(offset *string) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *ListStackSourcesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit string
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := qrLimit
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset string
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := qrOffset
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
