// Code generated by go-swagger; DO NOT EDIT.

package stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/koyeb/koyeb-cli/pkg/kclient/models"
)

// UpdateStack2Reader is a Reader for the UpdateStack2 structure.
type UpdateStack2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateStack2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateStack2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateStack2OK creates a UpdateStack2OK with default headers values
func NewUpdateStack2OK() *UpdateStack2OK {
	return &UpdateStack2OK{}
}

/*UpdateStack2OK handles this case with default header values.

A successful response.
*/
type UpdateStack2OK struct {
	Payload *models.StorageStackReply
}

func (o *UpdateStack2OK) Error() string {
	return fmt.Sprintf("[PATCH /v1/stacks/{id}][%d] updateStack2OK  %+v", 200, o.Payload)
}

func (o *UpdateStack2OK) GetPayload() *models.StorageStackReply {
	return o.Payload
}

func (o *UpdateStack2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StorageStackReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
