// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/koyeb/koyeb-cli/pkg/kclient/models"
)

// NewProfileResendEmailValidationParams creates a new ProfileResendEmailValidationParams object
// with the default values initialized.
func NewProfileResendEmailValidationParams() *ProfileResendEmailValidationParams {
	var ()
	return &ProfileResendEmailValidationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewProfileResendEmailValidationParamsWithTimeout creates a new ProfileResendEmailValidationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewProfileResendEmailValidationParamsWithTimeout(timeout time.Duration) *ProfileResendEmailValidationParams {
	var ()
	return &ProfileResendEmailValidationParams{

		timeout: timeout,
	}
}

// NewProfileResendEmailValidationParamsWithContext creates a new ProfileResendEmailValidationParams object
// with the default values initialized, and the ability to set a context for a request
func NewProfileResendEmailValidationParamsWithContext(ctx context.Context) *ProfileResendEmailValidationParams {
	var ()
	return &ProfileResendEmailValidationParams{

		Context: ctx,
	}
}

// NewProfileResendEmailValidationParamsWithHTTPClient creates a new ProfileResendEmailValidationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewProfileResendEmailValidationParamsWithHTTPClient(client *http.Client) *ProfileResendEmailValidationParams {
	var ()
	return &ProfileResendEmailValidationParams{
		HTTPClient: client,
	}
}

/*ProfileResendEmailValidationParams contains all the parameters to send to the API endpoint
for the profile resend email validation operation typically these are written to a http.Request
*/
type ProfileResendEmailValidationParams struct {

	/*Body*/
	Body models.AccountResendEmailValidationRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the profile resend email validation params
func (o *ProfileResendEmailValidationParams) WithTimeout(timeout time.Duration) *ProfileResendEmailValidationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the profile resend email validation params
func (o *ProfileResendEmailValidationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the profile resend email validation params
func (o *ProfileResendEmailValidationParams) WithContext(ctx context.Context) *ProfileResendEmailValidationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the profile resend email validation params
func (o *ProfileResendEmailValidationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the profile resend email validation params
func (o *ProfileResendEmailValidationParams) WithHTTPClient(client *http.Client) *ProfileResendEmailValidationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the profile resend email validation params
func (o *ProfileResendEmailValidationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the profile resend email validation params
func (o *ProfileResendEmailValidationParams) WithBody(body models.AccountResendEmailValidationRequest) *ProfileResendEmailValidationParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the profile resend email validation params
func (o *ProfileResendEmailValidationParams) SetBody(body models.AccountResendEmailValidationRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ProfileResendEmailValidationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
