// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/koyeb/koyeb-cli/pkg/kclient/models"
)

// AccountActivitiesGetAccountActivitiesReader is a Reader for the AccountActivitiesGetAccountActivities structure.
type AccountActivitiesGetAccountActivitiesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AccountActivitiesGetAccountActivitiesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAccountActivitiesGetAccountActivitiesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAccountActivitiesGetAccountActivitiesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewAccountActivitiesGetAccountActivitiesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewAccountActivitiesGetAccountActivitiesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewAccountActivitiesGetAccountActivitiesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAccountActivitiesGetAccountActivitiesOK creates a AccountActivitiesGetAccountActivitiesOK with default headers values
func NewAccountActivitiesGetAccountActivitiesOK() *AccountActivitiesGetAccountActivitiesOK {
	return &AccountActivitiesGetAccountActivitiesOK{}
}

/*AccountActivitiesGetAccountActivitiesOK handles this case with default header values.

A successful response.
*/
type AccountActivitiesGetAccountActivitiesOK struct {
	Payload *models.ActivityActivityList
}

func (o *AccountActivitiesGetAccountActivitiesOK) Error() string {
	return fmt.Sprintf("[GET /v1/account/activities][%d] accountActivitiesGetAccountActivitiesOK  %+v", 200, o.Payload)
}

func (o *AccountActivitiesGetAccountActivitiesOK) GetPayload() *models.ActivityActivityList {
	return o.Payload
}

func (o *AccountActivitiesGetAccountActivitiesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ActivityActivityList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAccountActivitiesGetAccountActivitiesBadRequest creates a AccountActivitiesGetAccountActivitiesBadRequest with default headers values
func NewAccountActivitiesGetAccountActivitiesBadRequest() *AccountActivitiesGetAccountActivitiesBadRequest {
	return &AccountActivitiesGetAccountActivitiesBadRequest{}
}

/*AccountActivitiesGetAccountActivitiesBadRequest handles this case with default header values.

Validation error
*/
type AccountActivitiesGetAccountActivitiesBadRequest struct {
	Payload *models.CommonErrorWithFields
}

func (o *AccountActivitiesGetAccountActivitiesBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/account/activities][%d] accountActivitiesGetAccountActivitiesBadRequest  %+v", 400, o.Payload)
}

func (o *AccountActivitiesGetAccountActivitiesBadRequest) GetPayload() *models.CommonErrorWithFields {
	return o.Payload
}

func (o *AccountActivitiesGetAccountActivitiesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonErrorWithFields)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAccountActivitiesGetAccountActivitiesForbidden creates a AccountActivitiesGetAccountActivitiesForbidden with default headers values
func NewAccountActivitiesGetAccountActivitiesForbidden() *AccountActivitiesGetAccountActivitiesForbidden {
	return &AccountActivitiesGetAccountActivitiesForbidden{}
}

/*AccountActivitiesGetAccountActivitiesForbidden handles this case with default header values.

Returned when the user does not have permission to access the resource.
*/
type AccountActivitiesGetAccountActivitiesForbidden struct {
	Payload *models.CommonError
}

func (o *AccountActivitiesGetAccountActivitiesForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/account/activities][%d] accountActivitiesGetAccountActivitiesForbidden  %+v", 403, o.Payload)
}

func (o *AccountActivitiesGetAccountActivitiesForbidden) GetPayload() *models.CommonError {
	return o.Payload
}

func (o *AccountActivitiesGetAccountActivitiesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAccountActivitiesGetAccountActivitiesNotFound creates a AccountActivitiesGetAccountActivitiesNotFound with default headers values
func NewAccountActivitiesGetAccountActivitiesNotFound() *AccountActivitiesGetAccountActivitiesNotFound {
	return &AccountActivitiesGetAccountActivitiesNotFound{}
}

/*AccountActivitiesGetAccountActivitiesNotFound handles this case with default header values.

Returned when the resource does not exist.
*/
type AccountActivitiesGetAccountActivitiesNotFound struct {
	Payload *models.CommonError
}

func (o *AccountActivitiesGetAccountActivitiesNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/account/activities][%d] accountActivitiesGetAccountActivitiesNotFound  %+v", 404, o.Payload)
}

func (o *AccountActivitiesGetAccountActivitiesNotFound) GetPayload() *models.CommonError {
	return o.Payload
}

func (o *AccountActivitiesGetAccountActivitiesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAccountActivitiesGetAccountActivitiesDefault creates a AccountActivitiesGetAccountActivitiesDefault with default headers values
func NewAccountActivitiesGetAccountActivitiesDefault(code int) *AccountActivitiesGetAccountActivitiesDefault {
	return &AccountActivitiesGetAccountActivitiesDefault{
		_statusCode: code,
	}
}

/*AccountActivitiesGetAccountActivitiesDefault handles this case with default header values.

An unexpected error response
*/
type AccountActivitiesGetAccountActivitiesDefault struct {
	_statusCode int

	Payload *models.GatewayruntimeError
}

// Code gets the status code for the account activities get account activities default response
func (o *AccountActivitiesGetAccountActivitiesDefault) Code() int {
	return o._statusCode
}

func (o *AccountActivitiesGetAccountActivitiesDefault) Error() string {
	return fmt.Sprintf("[GET /v1/account/activities][%d] accountActivities_GetAccountActivities default  %+v", o._statusCode, o.Payload)
}

func (o *AccountActivitiesGetAccountActivitiesDefault) GetPayload() *models.GatewayruntimeError {
	return o.Payload
}

func (o *AccountActivitiesGetAccountActivitiesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GatewayruntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
