name: test-compose-service
services:
  compose-go-service:
    git:
      repository: github.com/koyeb/example-golang
      branch: main
    ports:
      - port: 8000
    regions: ['par']
    scalings:
      - scopes: ['region:par']
        min: 1
        max: 1
    instance_types:
      - scopes: ['region:par']
        type: 'nano'
    envs:
      - scopes: ['region:par']
        key: 'PORT'
        value: '8000'

