name: compose-app
services:
  go-service:
    git:
      repository: github.com/koyeb/example-golang
      branch: main
    ports:
      - port: 8000
    regions: ['par']
    scalings:
      - scopes: ['region:par']
        min: 1
        max: 1
    instance_types:
      - scopes: ['region:par']
        type: 'nano'
    envs:
      - scopes: ['region:par']
        key: 'PORT'
        value: '8000'
  ping-service:
    docker:
      image: curlimages/curl
      command: 'sh'
      args: ['-c', 'while true; do curl go-service.compose-app.koyeb:8000; sleep 30; done']
    type: 'WORKER'
    regions: ['par']
    scalings:
      - scopes: ['region:par']
        min: 1
        max: 1
    instance_types:
      - scopes: ['region:par']
        type: 'nano'
    depends_on:
      - go-service
    
    
