// Code generated by go-swagger; DO NOT EDIT.

package billing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/koyeb/koyeb-cli/pkg/kclient/models"
)

// BillingCreateBillingInfoReader is a Reader for the BillingCreateBillingInfo structure.
type BillingCreateBillingInfoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BillingCreateBillingInfoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewBillingCreateBillingInfoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewBillingCreateBillingInfoBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewBillingCreateBillingInfoForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewBillingCreateBillingInfoNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewBillingCreateBillingInfoDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewBillingCreateBillingInfoOK creates a BillingCreateBillingInfoOK with default headers values
func NewBillingCreateBillingInfoOK() *BillingCreateBillingInfoOK {
	return &BillingCreateBillingInfoOK{}
}

/*BillingCreateBillingInfoOK handles this case with default header values.

A successful response.
*/
type BillingCreateBillingInfoOK struct {
	Payload *models.AccountBillingInfoReply
}

func (o *BillingCreateBillingInfoOK) Error() string {
	return fmt.Sprintf("[POST /v1/account/billing][%d] billingCreateBillingInfoOK  %+v", 200, o.Payload)
}

func (o *BillingCreateBillingInfoOK) GetPayload() *models.AccountBillingInfoReply {
	return o.Payload
}

func (o *BillingCreateBillingInfoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AccountBillingInfoReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBillingCreateBillingInfoBadRequest creates a BillingCreateBillingInfoBadRequest with default headers values
func NewBillingCreateBillingInfoBadRequest() *BillingCreateBillingInfoBadRequest {
	return &BillingCreateBillingInfoBadRequest{}
}

/*BillingCreateBillingInfoBadRequest handles this case with default header values.

Validation error
*/
type BillingCreateBillingInfoBadRequest struct {
	Payload *models.CommonErrorWithFields
}

func (o *BillingCreateBillingInfoBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/account/billing][%d] billingCreateBillingInfoBadRequest  %+v", 400, o.Payload)
}

func (o *BillingCreateBillingInfoBadRequest) GetPayload() *models.CommonErrorWithFields {
	return o.Payload
}

func (o *BillingCreateBillingInfoBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonErrorWithFields)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBillingCreateBillingInfoForbidden creates a BillingCreateBillingInfoForbidden with default headers values
func NewBillingCreateBillingInfoForbidden() *BillingCreateBillingInfoForbidden {
	return &BillingCreateBillingInfoForbidden{}
}

/*BillingCreateBillingInfoForbidden handles this case with default header values.

Returned when the user does not have permission to access the resource.
*/
type BillingCreateBillingInfoForbidden struct {
	Payload *models.CommonError
}

func (o *BillingCreateBillingInfoForbidden) Error() string {
	return fmt.Sprintf("[POST /v1/account/billing][%d] billingCreateBillingInfoForbidden  %+v", 403, o.Payload)
}

func (o *BillingCreateBillingInfoForbidden) GetPayload() *models.CommonError {
	return o.Payload
}

func (o *BillingCreateBillingInfoForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBillingCreateBillingInfoNotFound creates a BillingCreateBillingInfoNotFound with default headers values
func NewBillingCreateBillingInfoNotFound() *BillingCreateBillingInfoNotFound {
	return &BillingCreateBillingInfoNotFound{}
}

/*BillingCreateBillingInfoNotFound handles this case with default header values.

Returned when the resource does not exist.
*/
type BillingCreateBillingInfoNotFound struct {
	Payload *models.CommonError
}

func (o *BillingCreateBillingInfoNotFound) Error() string {
	return fmt.Sprintf("[POST /v1/account/billing][%d] billingCreateBillingInfoNotFound  %+v", 404, o.Payload)
}

func (o *BillingCreateBillingInfoNotFound) GetPayload() *models.CommonError {
	return o.Payload
}

func (o *BillingCreateBillingInfoNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBillingCreateBillingInfoDefault creates a BillingCreateBillingInfoDefault with default headers values
func NewBillingCreateBillingInfoDefault(code int) *BillingCreateBillingInfoDefault {
	return &BillingCreateBillingInfoDefault{
		_statusCode: code,
	}
}

/*BillingCreateBillingInfoDefault handles this case with default header values.

An unexpected error response
*/
type BillingCreateBillingInfoDefault struct {
	_statusCode int

	Payload *models.GatewayruntimeError
}

// Code gets the status code for the billing create billing info default response
func (o *BillingCreateBillingInfoDefault) Code() int {
	return o._statusCode
}

func (o *BillingCreateBillingInfoDefault) Error() string {
	return fmt.Sprintf("[POST /v1/account/billing][%d] billing_CreateBillingInfo default  %+v", o._statusCode, o.Payload)
}

func (o *BillingCreateBillingInfoDefault) GetPayload() *models.GatewayruntimeError {
	return o.Payload
}

func (o *BillingCreateBillingInfoDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GatewayruntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
