// Code generated by go-swagger; DO NOT EDIT.

package billing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/koyeb/koyeb-cli/pkg/kclient/models"
)

// UpdateBillingReader is a Reader for the UpdateBilling structure.
type UpdateBillingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateBillingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateBillingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateBillingOK creates a UpdateBillingOK with default headers values
func NewUpdateBillingOK() *UpdateBillingOK {
	return &UpdateBillingOK{}
}

/*UpdateBillingOK handles this case with default header values.

A successful response.
*/
type UpdateBillingOK struct {
	Payload *models.AccountBillingInfoReply
}

func (o *UpdateBillingOK) Error() string {
	return fmt.Sprintf("[PUT /v1/account/billing][%d] updateBillingOK  %+v", 200, o.Payload)
}

func (o *UpdateBillingOK) GetPayload() *models.AccountBillingInfoReply {
	return o.Payload
}

func (o *UpdateBillingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AccountBillingInfoReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
