// Code generated by go-swagger; DO NOT EDIT.

package billing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/koyeb/koyeb-cli/pkg/kclient/models"
)

// UpdateBilling2Reader is a Reader for the UpdateBilling2 structure.
type UpdateBilling2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateBilling2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateBilling2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateBilling2OK creates a UpdateBilling2OK with default headers values
func NewUpdateBilling2OK() *UpdateBilling2OK {
	return &UpdateBilling2OK{}
}

/*UpdateBilling2OK handles this case with default header values.

A successful response.
*/
type UpdateBilling2OK struct {
	Payload *models.AccountBillingInfoReply
}

func (o *UpdateBilling2OK) Error() string {
	return fmt.Sprintf("[PATCH /v1/account/billing][%d] updateBilling2OK  %+v", 200, o.Payload)
}

func (o *UpdateBilling2OK) GetPayload() *models.AccountBillingInfoReply {
	return o.Payload
}

func (o *UpdateBilling2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AccountBillingInfoReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
