// Code generated by go-swagger; DO NOT EDIT.

package store

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/koyeb/koyeb-cli/pkg/kclient/models"
)

// NewStoreUpdateStoreParams creates a new StoreUpdateStoreParams object
// with the default values initialized.
func NewStoreUpdateStoreParams() *StoreUpdateStoreParams {
	var ()
	return &StoreUpdateStoreParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStoreUpdateStoreParamsWithTimeout creates a new StoreUpdateStoreParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStoreUpdateStoreParamsWithTimeout(timeout time.Duration) *StoreUpdateStoreParams {
	var ()
	return &StoreUpdateStoreParams{

		timeout: timeout,
	}
}

// NewStoreUpdateStoreParamsWithContext creates a new StoreUpdateStoreParams object
// with the default values initialized, and the ability to set a context for a request
func NewStoreUpdateStoreParamsWithContext(ctx context.Context) *StoreUpdateStoreParams {
	var ()
	return &StoreUpdateStoreParams{

		Context: ctx,
	}
}

// NewStoreUpdateStoreParamsWithHTTPClient creates a new StoreUpdateStoreParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStoreUpdateStoreParamsWithHTTPClient(client *http.Client) *StoreUpdateStoreParams {
	var ()
	return &StoreUpdateStoreParams{
		HTTPClient: client,
	}
}

/*StoreUpdateStoreParams contains all the parameters to send to the API endpoint
for the store update store operation typically these are written to a http.Request
*/
type StoreUpdateStoreParams struct {

	/*Body*/
	Body *models.StorageStore
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the store update store params
func (o *StoreUpdateStoreParams) WithTimeout(timeout time.Duration) *StoreUpdateStoreParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the store update store params
func (o *StoreUpdateStoreParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the store update store params
func (o *StoreUpdateStoreParams) WithContext(ctx context.Context) *StoreUpdateStoreParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the store update store params
func (o *StoreUpdateStoreParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the store update store params
func (o *StoreUpdateStoreParams) WithHTTPClient(client *http.Client) *StoreUpdateStoreParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the store update store params
func (o *StoreUpdateStoreParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the store update store params
func (o *StoreUpdateStoreParams) WithBody(body *models.StorageStore) *StoreUpdateStoreParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the store update store params
func (o *StoreUpdateStoreParams) SetBody(body *models.StorageStore) {
	o.Body = body
}

// WithID adds the id to the store update store params
func (o *StoreUpdateStoreParams) WithID(id string) *StoreUpdateStoreParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the store update store params
func (o *StoreUpdateStoreParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *StoreUpdateStoreParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
