// Code generated by go-swagger; DO NOT EDIT.

package secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/koyeb/koyeb-cli/pkg/kclient/models"
)

// NewNewSecretParams creates a new NewSecretParams object
// with the default values initialized.
func NewNewSecretParams() *NewSecretParams {
	var ()
	return &NewSecretParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewNewSecretParamsWithTimeout creates a new NewSecretParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewNewSecretParamsWithTimeout(timeout time.Duration) *NewSecretParams {
	var ()
	return &NewSecretParams{

		timeout: timeout,
	}
}

// NewNewSecretParamsWithContext creates a new NewSecretParams object
// with the default values initialized, and the ability to set a context for a request
func NewNewSecretParamsWithContext(ctx context.Context) *NewSecretParams {
	var ()
	return &NewSecretParams{

		Context: ctx,
	}
}

// NewNewSecretParamsWithHTTPClient creates a new NewSecretParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNewSecretParamsWithHTTPClient(client *http.Client) *NewSecretParams {
	var ()
	return &NewSecretParams{
		HTTPClient: client,
	}
}

/*NewSecretParams contains all the parameters to send to the API endpoint
for the new secret operation typically these are written to a http.Request
*/
type NewSecretParams struct {

	/*Body*/
	Body *models.StorageNewSecret

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the new secret params
func (o *NewSecretParams) WithTimeout(timeout time.Duration) *NewSecretParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the new secret params
func (o *NewSecretParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the new secret params
func (o *NewSecretParams) WithContext(ctx context.Context) *NewSecretParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the new secret params
func (o *NewSecretParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the new secret params
func (o *NewSecretParams) WithHTTPClient(client *http.Client) *NewSecretParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the new secret params
func (o *NewSecretParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the new secret params
func (o *NewSecretParams) WithBody(body *models.StorageNewSecret) *NewSecretParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the new secret params
func (o *NewSecretParams) SetBody(body *models.StorageNewSecret) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *NewSecretParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
