// Code generated by go-swagger; DO NOT EDIT.

package secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/koyeb/koyeb-cli/pkg/kclient/models"
)

// NewSecretsNewSecretParams creates a new SecretsNewSecretParams object
// with the default values initialized.
func NewSecretsNewSecretParams() *SecretsNewSecretParams {
	var ()
	return &SecretsNewSecretParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSecretsNewSecretParamsWithTimeout creates a new SecretsNewSecretParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSecretsNewSecretParamsWithTimeout(timeout time.Duration) *SecretsNewSecretParams {
	var ()
	return &SecretsNewSecretParams{

		timeout: timeout,
	}
}

// NewSecretsNewSecretParamsWithContext creates a new SecretsNewSecretParams object
// with the default values initialized, and the ability to set a context for a request
func NewSecretsNewSecretParamsWithContext(ctx context.Context) *SecretsNewSecretParams {
	var ()
	return &SecretsNewSecretParams{

		Context: ctx,
	}
}

// NewSecretsNewSecretParamsWithHTTPClient creates a new SecretsNewSecretParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSecretsNewSecretParamsWithHTTPClient(client *http.Client) *SecretsNewSecretParams {
	var ()
	return &SecretsNewSecretParams{
		HTTPClient: client,
	}
}

/*SecretsNewSecretParams contains all the parameters to send to the API endpoint
for the secrets new secret operation typically these are written to a http.Request
*/
type SecretsNewSecretParams struct {

	/*Body*/
	Body *models.StorageNewSecret

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the secrets new secret params
func (o *SecretsNewSecretParams) WithTimeout(timeout time.Duration) *SecretsNewSecretParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the secrets new secret params
func (o *SecretsNewSecretParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the secrets new secret params
func (o *SecretsNewSecretParams) WithContext(ctx context.Context) *SecretsNewSecretParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the secrets new secret params
func (o *SecretsNewSecretParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the secrets new secret params
func (o *SecretsNewSecretParams) WithHTTPClient(client *http.Client) *SecretsNewSecretParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the secrets new secret params
func (o *SecretsNewSecretParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the secrets new secret params
func (o *SecretsNewSecretParams) WithBody(body *models.StorageNewSecret) *SecretsNewSecretParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the secrets new secret params
func (o *SecretsNewSecretParams) SetBody(body *models.StorageNewSecret) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SecretsNewSecretParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
