// Code generated by go-swagger; DO NOT EDIT.

package secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSecretsListSecretsParams creates a new SecretsListSecretsParams object
// with the default values initialized.
func NewSecretsListSecretsParams() *SecretsListSecretsParams {
	var ()
	return &SecretsListSecretsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSecretsListSecretsParamsWithTimeout creates a new SecretsListSecretsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSecretsListSecretsParamsWithTimeout(timeout time.Duration) *SecretsListSecretsParams {
	var ()
	return &SecretsListSecretsParams{

		timeout: timeout,
	}
}

// NewSecretsListSecretsParamsWithContext creates a new SecretsListSecretsParams object
// with the default values initialized, and the ability to set a context for a request
func NewSecretsListSecretsParamsWithContext(ctx context.Context) *SecretsListSecretsParams {
	var ()
	return &SecretsListSecretsParams{

		Context: ctx,
	}
}

// NewSecretsListSecretsParamsWithHTTPClient creates a new SecretsListSecretsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSecretsListSecretsParamsWithHTTPClient(client *http.Client) *SecretsListSecretsParams {
	var ()
	return &SecretsListSecretsParams{
		HTTPClient: client,
	}
}

/*SecretsListSecretsParams contains all the parameters to send to the API endpoint
for the secrets list secrets operation typically these are written to a http.Request
*/
type SecretsListSecretsParams struct {

	/*Limit*/
	Limit *string
	/*Name*/
	Name *string
	/*Offset*/
	Offset *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the secrets list secrets params
func (o *SecretsListSecretsParams) WithTimeout(timeout time.Duration) *SecretsListSecretsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the secrets list secrets params
func (o *SecretsListSecretsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the secrets list secrets params
func (o *SecretsListSecretsParams) WithContext(ctx context.Context) *SecretsListSecretsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the secrets list secrets params
func (o *SecretsListSecretsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the secrets list secrets params
func (o *SecretsListSecretsParams) WithHTTPClient(client *http.Client) *SecretsListSecretsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the secrets list secrets params
func (o *SecretsListSecretsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the secrets list secrets params
func (o *SecretsListSecretsParams) WithLimit(limit *string) *SecretsListSecretsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the secrets list secrets params
func (o *SecretsListSecretsParams) SetLimit(limit *string) {
	o.Limit = limit
}

// WithName adds the name to the secrets list secrets params
func (o *SecretsListSecretsParams) WithName(name *string) *SecretsListSecretsParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the secrets list secrets params
func (o *SecretsListSecretsParams) SetName(name *string) {
	o.Name = name
}

// WithOffset adds the offset to the secrets list secrets params
func (o *SecretsListSecretsParams) WithOffset(offset *string) *SecretsListSecretsParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the secrets list secrets params
func (o *SecretsListSecretsParams) SetOffset(offset *string) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *SecretsListSecretsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit string
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := qrLimit
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset string
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := qrOffset
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
