// Code generated by go-swagger; DO NOT EDIT.

package secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/koyeb/koyeb-cli/pkg/kclient/models"
)

// UpdateSecret2Reader is a Reader for the UpdateSecret2 structure.
type UpdateSecret2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateSecret2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateSecret2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateSecret2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateSecret2Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateSecret2NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateSecret2OK creates a UpdateSecret2OK with default headers values
func NewUpdateSecret2OK() *UpdateSecret2OK {
	return &UpdateSecret2OK{}
}

/*UpdateSecret2OK handles this case with default header values.

A successful response.
*/
type UpdateSecret2OK struct {
	Payload *models.StorageSecretReply
}

func (o *UpdateSecret2OK) Error() string {
	return fmt.Sprintf("[PATCH /v1/secrets/{id}][%d] updateSecret2OK  %+v", 200, o.Payload)
}

func (o *UpdateSecret2OK) GetPayload() *models.StorageSecretReply {
	return o.Payload
}

func (o *UpdateSecret2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StorageSecretReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateSecret2BadRequest creates a UpdateSecret2BadRequest with default headers values
func NewUpdateSecret2BadRequest() *UpdateSecret2BadRequest {
	return &UpdateSecret2BadRequest{}
}

/*UpdateSecret2BadRequest handles this case with default header values.

Validation error
*/
type UpdateSecret2BadRequest struct {
	Payload *models.CommonErrorWithFields
}

func (o *UpdateSecret2BadRequest) Error() string {
	return fmt.Sprintf("[PATCH /v1/secrets/{id}][%d] updateSecret2BadRequest  %+v", 400, o.Payload)
}

func (o *UpdateSecret2BadRequest) GetPayload() *models.CommonErrorWithFields {
	return o.Payload
}

func (o *UpdateSecret2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonErrorWithFields)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateSecret2Forbidden creates a UpdateSecret2Forbidden with default headers values
func NewUpdateSecret2Forbidden() *UpdateSecret2Forbidden {
	return &UpdateSecret2Forbidden{}
}

/*UpdateSecret2Forbidden handles this case with default header values.

Returned when the user does not have permission to access the resource.
*/
type UpdateSecret2Forbidden struct {
	Payload *models.CommonError
}

func (o *UpdateSecret2Forbidden) Error() string {
	return fmt.Sprintf("[PATCH /v1/secrets/{id}][%d] updateSecret2Forbidden  %+v", 403, o.Payload)
}

func (o *UpdateSecret2Forbidden) GetPayload() *models.CommonError {
	return o.Payload
}

func (o *UpdateSecret2Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateSecret2NotFound creates a UpdateSecret2NotFound with default headers values
func NewUpdateSecret2NotFound() *UpdateSecret2NotFound {
	return &UpdateSecret2NotFound{}
}

/*UpdateSecret2NotFound handles this case with default header values.

Returned when the resource does not exist.
*/
type UpdateSecret2NotFound struct {
	Payload *models.CommonError
}

func (o *UpdateSecret2NotFound) Error() string {
	return fmt.Sprintf("[PATCH /v1/secrets/{id}][%d] updateSecret2NotFound  %+v", 404, o.Payload)
}

func (o *UpdateSecret2NotFound) GetPayload() *models.CommonError {
	return o.Payload
}

func (o *UpdateSecret2NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
