// Code generated by go-swagger; DO NOT EDIT.

package signup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/koyeb/koyeb-cli/pkg/kclient/models"
)

// NewPasswordlessLoginParams creates a new PasswordlessLoginParams object
// with the default values initialized.
func NewPasswordlessLoginParams() *PasswordlessLoginParams {
	var ()
	return &PasswordlessLoginParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPasswordlessLoginParamsWithTimeout creates a new PasswordlessLoginParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPasswordlessLoginParamsWithTimeout(timeout time.Duration) *PasswordlessLoginParams {
	var ()
	return &PasswordlessLoginParams{

		timeout: timeout,
	}
}

// NewPasswordlessLoginParamsWithContext creates a new PasswordlessLoginParams object
// with the default values initialized, and the ability to set a context for a request
func NewPasswordlessLoginParamsWithContext(ctx context.Context) *PasswordlessLoginParams {
	var ()
	return &PasswordlessLoginParams{

		Context: ctx,
	}
}

// NewPasswordlessLoginParamsWithHTTPClient creates a new PasswordlessLoginParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPasswordlessLoginParamsWithHTTPClient(client *http.Client) *PasswordlessLoginParams {
	var ()
	return &PasswordlessLoginParams{
		HTTPClient: client,
	}
}

/*PasswordlessLoginParams contains all the parameters to send to the API endpoint
for the passwordless login operation typically these are written to a http.Request
*/
type PasswordlessLoginParams struct {

	/*Body*/
	Body *models.AccountPasswordlessLoginRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the passwordless login params
func (o *PasswordlessLoginParams) WithTimeout(timeout time.Duration) *PasswordlessLoginParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the passwordless login params
func (o *PasswordlessLoginParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the passwordless login params
func (o *PasswordlessLoginParams) WithContext(ctx context.Context) *PasswordlessLoginParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the passwordless login params
func (o *PasswordlessLoginParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the passwordless login params
func (o *PasswordlessLoginParams) WithHTTPClient(client *http.Client) *PasswordlessLoginParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the passwordless login params
func (o *PasswordlessLoginParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the passwordless login params
func (o *PasswordlessLoginParams) WithBody(body *models.AccountPasswordlessLoginRequest) *PasswordlessLoginParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the passwordless login params
func (o *PasswordlessLoginParams) SetBody(body *models.AccountPasswordlessLoginRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PasswordlessLoginParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
