on: [push]

name: Release

jobs:
  check:
    runs-on: ubuntu-latest
    if: startswith(github.ref, 'refs/heads')
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Run tests
        run: make test
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    if: startswith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
